// GENERATED by scripts/gen-color-range.py; see linux/patches/color-range.patch.
#pragma once
#include <stddef.h>
#include <stdint.h>

// Select > Color Range over premultiplied RGBA (as above). A pixel matches when every color channel is within
// `fuzziness` of one of the `includeCount` colors in `include` and of none in `exclude` (straight sRGB, 3 bytes
// each). Transparent pixels never match. With `invert`, the pixels that don't match are selected instead. Writes
// 255 for selected, 0 elsewhere, into `mask`, and returns the number selected.
long color_range_mask(const uint8_t *rgba, size_t width, size_t height, size_t stride,
                      const uint8_t *include, int includeCount, const uint8_t *exclude, int excludeCount,
                      int fuzziness, int invert, uint8_t *mask);
