// host_run.cpp — the Qt host entry called by the Swift composition root.
//
// The Linux port's composition root is inverted: a Swift `@main`
// (Sources/CompositorHostBootstrap/hostMain.swift) bootstraps the Swift runtime
// + Foundation (which a C++ main cannot on the Freedesktop Swift 6.3 SDK), then
// calls this `compositor_host_run` C entry to run the Qt Widgets shell. The Qt
// host in turn calls back into the Swift core through the `compositor_session_*`
// C ABI (ENG-1). The standalone CMake `compositor` target keeps its own `main`
// (host/main.cpp) for the C++-only build path.
//
// This entry creates the real `MainWindow` (host/MainWindow.h, Q_OBJECT). Its
// moc output (host/moc_MainWindow.cpp) is generated by `moc` and committed so
// SwiftPM can build it without AUTOMOC. The Flatpak build rebuilds the same
// window via CMake/AUTOMOC; this SwiftPM path proves the moc'd-Qt -> Swift-@main
// link. The headless proof processes pending paint events without entering the
// blocking event loop; the Flatpak app calls app.exec() here.

#include <QApplication>
#include <QCoreApplication>

#include "compositor_host_run.h"
#include "SessionWindow.h"

extern "C" int compositor_host_run(int argc, char **argv) {
    QApplication app(argc, argv);
    app.setApplicationName("Compositor");
    app.setOrganizationName("Compositor");
    // SessionWindow (moc'd Q_OBJECT) drives the Swift core via compositor_session_*
    // and paints the composited RGBA — the architecture the Flatpak build ships.
    // The richer MainWindow (C-kernels Qt shell) is the C++-only build path's window.
    SessionWindow window;
    window.show();
    // Headless-safe: flush pending paint events (triggers SessionWindow::paintEvent
    // drawing the C-ABI-rendered QImage) without the blocking event loop.
    QCoreApplication::processEvents();
    return 0;
}