#include <QJsonArray>
#include <QKeyEvent>
#include <QMouseEvent>
// host_run.cpp — the Qt host entry called by the Swift composition root.
//
// The Linux port's composition root is inverted: a Swift `@main`
// (Sources/CompositorHostBootstrap/hostMain.swift) bootstraps the Swift runtime
// + Foundation (which a C++ main cannot on the Freedesktop Swift 6.3 SDK), then
// calls this `compositor_host_run` C entry to run the Qt Widgets shell. The Qt
// host in turn calls back into the Swift core through the `compositor_session_*`
// C ABI (ENG-1). This is the only entry point — there is no separate C++-main
// build path.
//
// This entry creates the real `SessionWindow` (host/SessionWindow.h, Q_OBJECT).
// Its moc output (host/moc_SessionWindow.cpp) is generated by `moc` and committed
// so SwiftPM can build it without AUTOMOC. The Flatpak build rebuilds the same
// window via CMake/AUTOMOC; this SwiftPM path proves the moc'd-Qt -> Swift-@main
// link. The headless proof processes pending paint events without entering the
// blocking event loop; the Flatpak app calls app.exec() here.

#include <QApplication>
#include <QDialog>
#include <QContextMenuEvent>
#include <QTimer>
#include <QLabel>
#include <QPushButton>
#include <algorithm>
#include <QDropEvent>
#include <QMimeData>
#include <QAction>
#include <QElapsedTimer>
#include <QCursor>
#include <QHoverEvent>
#include <QNativeGestureEvent>
#include <QPointingDevice>
#include <QClipboard>
#include <cstdio>
#include <QCoreApplication>
#include <QProcessEnvironment>
#include <QTemporaryDir>
#include <QFile>
#include <QDir>

#include "compositor_host_run.h"
#include "EditorDialogs.h"
#include "ColorPickerDialog.h"
#include "SystemClipboard.h"
#include "SwiftUIQtRenderer.h"
#include <cmath>
#include <clocale>
#include <QDockWidget>
#include <QMenuBar>
#include <QMenu>
#include <QComboBox>
#include <QJsonDocument>
#include <QJsonObject>
#include <vector>
#include <QIcon>
#include <QStyleFactory>
#include <QFontDatabase>
#include <QDir>
#include <QCoreApplication>
#include "SessionWindow.h"

#if defined(COMPOSITOR_SKIA_BRIDGE)
#include "SkiaBridge.h"
#endif

extern "C" int compositor_qt_imageio_install(void);
extern "C" int compositor_raw_install(void);
extern "C" int32_t compositor_install_subject_model(void);
extern "C" void compositor_app_did_become_active(void);

extern "C" int compositor_host_run(int argc, char **argv) {
    QApplication app(argc, argv);
    // QApplication adopts the environment's C locale; printf-style formatting (upstream's String(format:)) must stay
    // POSIX, as it is on macOS ("128.33", not "128,33"). Locale-aware formatting goes through Foundation's Locale.
    setlocale(LC_NUMERIC, "C");
    app.setStyle(QStyleFactory::create(QStringLiteral("Fusion")));
    // macOS draws its UI in the system font (SF Pro) at 13 pt; Inter is its open stand-in (MACOS_UI_PARITY_RULES.md
    // §4.2), shipped with the app, with Noto Sans as the fallback.
    {
        QString family;
        for (const QString &path : {QCoreApplication::applicationDirPath() + QStringLiteral("/../share/compositor/fonts"),
                                    QDir::currentPath() + QStringLiteral("/third_party/fonts/inter")}) {
            const QDir dir(path);
            for (const QString &file : dir.entryList({QStringLiteral("Inter-*.ttf")}, QDir::Files)) {
                const int id = QFontDatabase::addApplicationFont(dir.filePath(file));
                if (id >= 0 && family.isEmpty() && !QFontDatabase::applicationFontFamilies(id).isEmpty())
                    family = QFontDatabase::applicationFontFamilies(id).first();
            }
            if (!family.isEmpty()) break;
        }
        QFont ui(family.isEmpty() ? QStringLiteral("Noto Sans") : family);
        ui.setPixelSize(13);
        ui.setHintingPreference(QFont::PreferNoHinting);   // CoreText doesn't hint either
        app.setFont(ui);
    }
    // Qt image plugins become the ImageIO compat backend (JPEG/TIFF/WebP/... beyond the portable PNG codec).
    compositor_qt_imageio_install();
    compositor_raw_install();   // camera RAW via LibRaw (a no-op when built without it)
    systemclipboard::install();   // NSPasteboard.general is the desktop clipboard, as on macOS
    compositor_install_subject_model();   // Select Subject / Remove Background: U²-Net-small when bundled
    // NSApplication.didBecomeActiveNotification: coming back to the app (upstream re-checks its recent projects).
    QObject::connect(qApp, &QGuiApplication::applicationStateChanged, qApp, [](Qt::ApplicationState state) {
        if (state == Qt::ApplicationActive) compositor_app_did_become_active();
    });
    app.setApplicationName("Compositor");
    app.setOrganizationName("Compositor");
    app.setDesktopFileName("com.wonderassembly.Compositor");

    QIcon appIcon;
    const int iconSizes[] = {16, 32, 64, 128, 256, 512, 1024};
    for (int s : iconSizes) {
        const QString p1 = QStringLiteral("Compositor/Assets.xcassets/AppIcon.appiconset/app-icon-%1.png").arg(s);
        if (QFile::exists(p1)) {
            appIcon.addFile(p1);
        } else {
            const QString p2 = QDir::homePath() + QStringLiteral("/.local/share/icons/hicolor/%1x%1/apps/com.wonderassembly.Compositor.png").arg(s);
            if (QFile::exists(p2)) appIcon.addFile(p2);
        }
    }
    if (!appIcon.isNull()) {
        app.setWindowIcon(appIcon);
    }

#if defined(COMPOSITOR_SKIA_BRIDGE)
    // Plan §6 startup: try Vulkan, fall back to Raster. The renderer backs
    // the Swift CGContextCompat shim; on any failure the Swift
    // DocumentRenderer remains the ultimate fallback.
    CompRendererKind kind = COMP_RENDERER_RASTER;
    CompRenderer *renderer = compositor_renderer_create(0, &kind);
    if (renderer) compositor_renderer_activate(renderer);
#endif
    // SessionWindow (moc'd Q_OBJECT) drives the Swift core via compositor_session_*
    // and paints the composited RGBA — the architecture the Flatpak build ships.
    SessionWindow window;
    if (!appIcon.isNull()) {
        window.setWindowIcon(appIcon);
    }
    for (int i = 1; i < argc; ++i) {
        if (!argv[i]) continue;
        QString arg = QString::fromLocal8Bit(argv[i]);
        if (arg.startsWith(QLatin1Char('-'))) continue;
        if (QFile::exists(arg)) {
            if (arg.endsWith(QStringLiteral(".cproject"), Qt::CaseInsensitive)) {
                window.loadProject(arg);
            } else {
                window.importImage(arg);
            }
            break;
        }
    }
    if (qEnvironmentVariable("COMPOSITOR_GRAB_PATH").isEmpty() && !QCoreApplication::arguments().filter(QStringLiteral("-smoke")).size())
        window.restoreWindowPlacement();
    window.show();
    if (!qEnvironmentVariable("COMPOSITOR_GRAB_PATH").isEmpty()) {
        // COMPOSITOR_GRAB_SIZE=WxH: the window at that size first (e.g. tall enough to show the whole tool rail).
        if (const QStringList wh = qEnvironmentVariable("COMPOSITOR_GRAB_SIZE").split(QLatin1Char('x')); wh.size() == 2) {
            window.resize(wh[0].toInt(), wh[1].toInt());
            for (int i = 0; i < 10; ++i) QCoreApplication::processEvents();
        }
        const QString toolArg = qEnvironmentVariable("COMPOSITOR_GRAB_TOOL");
        if (toolArg == "move") window.setTool(SessionWindow::Tool::Move);
        else if (toolArg == "brush") window.setTool(SessionWindow::Tool::Brush);
        else if (toolArg == "crop") window.setTool(SessionWindow::Tool::Crop);
        else if (toolArg == "zoom") window.setTool(SessionWindow::Tool::Zoom);
        else if (toolArg == "lasso") window.setTool(SessionWindow::Tool::Lasso);
        else if (toolArg == "marquee") window.setTool(SessionWindow::Tool::Marquee);
        else if (toolArg == "gradient") window.setTool(SessionWindow::Tool::Gradient);
        else if (toolArg == "shape") window.setTool(SessionWindow::Tool::Shape);
        else if (toolArg == "type") window.setTool(SessionWindow::Tool::Type);
        else if (toolArg == "spotHealing") window.setTool(SessionWindow::Tool::SpotHealing);
        else if (toolArg == "cloneStamp") window.setTool(SessionWindow::Tool::CloneStamp);
        if (!qEnvironmentVariable("COMPOSITOR_GRAB_SELECTION_MODE").isEmpty()) {
            const QString mode = qEnvironmentVariable("COMPOSITOR_GRAB_SELECTION_MODE");
            QJsonObject cmd;
            cmd["version"] = 1;
            cmd["action"] = "setSelectionMode";
            cmd["kind"] = mode;
            window.sendCommand(cmd);
            window.updateOptionsBar();
        }
        // COMPOSITOR_GRAB_BRUSH="hardness,opacity,smoothing" (0-1, 0-1, 0-100): set in the session as upstream's options
        // bar does, before COMPOSITOR_GRAB_DRAG paints with them.
        if (!qEnvironmentVariable("COMPOSITOR_GRAB_BRUSH").isEmpty()) {
            const QStringList b = qEnvironmentVariable("COMPOSITOR_GRAB_BRUSH").split(',');
            if (b.size() == 3) {
                window.sendCommand({{"version", 1}, {"action", "setBrushSettings"},
                                    {"parameters", QJsonObject{{"hardness", b[0].toDouble()}, {"opacity", b[1].toDouble()},
                                                               {"smoothing", b[2].toDouble()}}}});
            }
        }
        // COMPOSITOR_GRAB_EFFECT="Drop Shadow" (a LayerEffectKind): added to the active layer as the Layers panel's fx menu
        // does, which opens its floating panel.
        if (!qEnvironmentVariable("COMPOSITOR_GRAB_EFFECT").isEmpty()) {
            window.sendCommand({{"version", 1}, {"action", "addLayerEffect"}, {"kind", qEnvironmentVariable("COMPOSITOR_GRAB_EFFECT")}});
            window.updateFloatingPanels();
            QElapsedTimer settle; settle.start();   // let the pump render the effect's preview
            while (settle.elapsed() < 400) QCoreApplication::processEvents(QEventLoop::AllEvents, 20);
            // COMPOSITOR_GRAB_EFFECT_COMMIT=1: then its panel's OK, as the user confirms it.
            if (qEnvironmentVariableIsSet("COMPOSITOR_GRAB_EFFECT_COMMIT")) {
                for (QWidget *top : QApplication::topLevelWidgets()) {
                    if (!top->isVisible() || top == &window) continue;
                    for (QPushButton *button : top->findChildren<QPushButton *>())
                        if (button->isVisible() && button->text() == QLatin1String("OK")) { button->click(); break; }
                }
                QElapsedTimer done; done.start();
                while (done.elapsed() < 300) QCoreApplication::processEvents(QEventLoop::AllEvents, 20);
            }
        }
        // COMPOSITOR_GRAB_SAVE_PROJECT=<package path>: the document saved there, as File > Save does.
        if (!qEnvironmentVariable("COMPOSITOR_GRAB_SAVE_PROJECT").isEmpty())
            std::fprintf(stderr, "SAVE %s\n", window.saveProject(qEnvironmentVariable("COMPOSITOR_GRAB_SAVE_PROJECT")) ? "ok" : "failed");
        // COMPOSITOR_GRAB_CLIPBOARD_IMAGE=<file>: that picture on the desktop clipboard, as another application puts it.
        if (!qEnvironmentVariable("COMPOSITOR_GRAB_CLIPBOARD_IMAGE").isEmpty())
            QApplication::clipboard()->setImage(QImage(qEnvironmentVariable("COMPOSITOR_GRAB_CLIPBOARD_IMAGE")));
        // COMPOSITOR_GRAB_MENU_ITEM="Menu/Item[;Menu/Item...]": the menu bar's items (upstream's menus), chosen by title.
        for (const QString &spec : qEnvironmentVariable("COMPOSITOR_GRAB_MENU_ITEM").split(QLatin1Char(';'), Qt::SkipEmptyParts)) {
            const QStringList parts = spec.split(QLatin1Char('/'));
            for (QAction *top : window.menuBar()->actions()) {
                if (!top->isVisible() || !top->menu() || top->text().trimmed() != parts.value(0)) continue;
                emit top->menu()->aboutToShow();
                QMenu *menu = top->menu();
                for (int level = 1; menu && level < parts.size(); ++level) {
                    QMenu *next = nullptr;
                    // A title with a slash in it ("Hue/Saturation…") spans two parts.
                    QString title = parts[level];
                    auto titled = [&](const QString &t) {
                        for (QAction *item : menu->actions())
                            if (QString(item->text()).replace(QStringLiteral("&&"), QStringLiteral("&")) == t) return true;
                        return false;
                    };
                    while (!titled(title) && level + 1 < parts.size()) title += QLatin1Char('/') + parts[++level];
                    for (QAction *item : menu->actions()) {
                        if (QString(item->text()).replace(QStringLiteral("&&"), QStringLiteral("&")) != title) continue;
                        if (item->menu()) next = item->menu(); else item->trigger();
                        break;
                    }
                    menu = next;
                }
            }
            for (int i = 0; i < 20; ++i) QCoreApplication::processEvents();
        }
        // COMPOSITOR_GRAB_COMMAND=<JSON object>[;<JSON object>...]: bridge commands sent as the shell would.
        for (const QString &json : qEnvironmentVariable("COMPOSITOR_GRAB_COMMAND").split(QLatin1Char(';'), Qt::SkipEmptyParts)) {
            window.sendCommand(QJsonDocument::fromJson(json.toUtf8()).object());
            window.updateFloatingPanels();
            for (int i = 0; i < 20; ++i) QCoreApplication::processEvents();
        }
        // COMPOSITOR_GRAB_CURSOR="x,y" (document pixels): hover the canvas there and save its cursor as <path>.cursor.png.
        if (!qEnvironmentVariable("COMPOSITOR_GRAB_CURSOR").isEmpty()) {
            const QStringList v = qEnvironmentVariable("COMPOSITOR_GRAB_CURSOR").split(QLatin1Char(','));
            if (QWidget *canvas = window.findChild<QWidget *>(QStringLiteral("editorCanvas")); canvas && v.size() == 2) {
                window.show();
                for (int i = 0; i < 10; ++i) QCoreApplication::processEvents();
                const QPointF at = window.documentToCanvasPoint(QPointF(v[0].toDouble(), v[1].toDouble()));
                QMouseEvent move(QEvent::MouseMove, at, canvas->mapToGlobal(at), Qt::NoButton, Qt::NoButton, Qt::NoModifier);
                QCoreApplication::sendEvent(canvas, &move);
                const QCursor cursor = canvas->cursor();
                QPixmap picture = cursor.pixmap();
                if (picture.isNull()) { picture = QPixmap(24, 24); picture.fill(Qt::magenta); }
                picture.save(qEnvironmentVariable("COMPOSITOR_GRAB_PATH") + ".cursor.png");
                qInfo("cursor shape %d hot %d,%d", int(cursor.shape()), cursor.hotSpot().x(), cursor.hotSpot().y());
            }
        }
        // COMPOSITOR_GRAB_KEYS="m,m,shift+u,2": plain key presses at the canvas, as typed with it focused.
        for (const QString &spec : qEnvironmentVariable("COMPOSITOR_GRAB_KEYS").split(QLatin1Char(','), Qt::SkipEmptyParts)) {
            QWidget *canvas = window.findChild<QWidget *>(QStringLiteral("editorCanvas"));
            if (!canvas) break;
            const bool shift = spec.startsWith(QLatin1String("shift+"));
            QString text = shift ? spec.mid(6) : spec;
            if (shift) text = text.toUpper();
            const int key = text.isEmpty() ? 0 : text.toUpper().at(0).unicode();
            QKeyEvent press(QEvent::KeyPress, key, shift ? Qt::ShiftModifier : Qt::NoModifier, text);
            QCoreApplication::sendEvent(canvas, &press);
            for (int i = 0; i < 5; ++i) QCoreApplication::processEvents();
        }
        // COMPOSITOR_GRAB_BLEND_HOVER=<mode>: open the Layers panel's blend menu and hover that mode (menu left open).
        if (!qEnvironmentVariable("COMPOSITOR_GRAB_BLEND_HOVER").isEmpty()) {
            for (QComboBox *combo : window.findChildren<QComboBox *>()) {
                const int index = combo->findText(qEnvironmentVariable("COMPOSITOR_GRAB_BLEND_HOVER"));
                if (index < 0 || !combo->isVisible()) continue;
                combo->showPopup();
                emit combo->highlighted(index);
                for (int i = 0; i < 20; ++i) QCoreApplication::processEvents();
                break;
            }
        }
        // COMPOSITOR_GRAB_EYE_SWIPE="from,to": press the eye of Layers row `from` (top first), drag to row `to`, let go.
        if (!qEnvironmentVariable("COMPOSITOR_GRAB_EYE_SWIPE").isEmpty()) {
            const QStringList v = qEnvironmentVariable("COMPOSITOR_GRAB_EYE_SWIPE").split(QLatin1Char(','));
            QList<QWidget *> eyes;
            for (QWidget *w : window.findChildren<QWidget *>())
                if (w->property("swipeGroup").toString() == QLatin1String("layerEyes") && w->isVisible()) eyes << w;
            std::sort(eyes.begin(), eyes.end(), [](QWidget *a, QWidget *b) { return a->mapToGlobal(QPoint()).y() < b->mapToGlobal(QPoint()).y(); });
            // One per row (a rebuilt panel can leave an old copy behind for a moment).
            eyes.erase(std::unique(eyes.begin(), eyes.end(), [](QWidget *a, QWidget *b) { return a->mapToGlobal(QPoint()).y() == b->mapToGlobal(QPoint()).y(); }), eyes.end());
            const int from = v.value(0).toInt(), to = v.value(1).toInt();
            if (from < eyes.size() && to < eyes.size()) {
                QWidget *start = eyes[from];
                const QPointF local(start->width() / 2.0, start->height() / 2.0);
                QMouseEvent press(QEvent::MouseButtonPress, local, start->mapToGlobal(local), Qt::LeftButton, Qt::LeftButton, Qt::NoModifier);
                QCoreApplication::sendEvent(start, &press);
                const int step = from <= to ? 1 : -1;
                for (int i = from; i != to + step; i += step) {
                    const QPointF global = eyes[i]->mapToGlobal(QPointF(eyes[i]->width() / 2.0, eyes[i]->height() / 2.0));
                    QMouseEvent move(QEvent::MouseMove, start->mapFromGlobal(global), global, Qt::NoButton, Qt::LeftButton, Qt::NoModifier);
                    QCoreApplication::sendEvent(start, &move);
                }
                QMouseEvent release(QEvent::MouseButtonRelease, local, start->mapToGlobal(local), Qt::LeftButton, Qt::NoButton, Qt::NoModifier);
                QCoreApplication::sendEvent(start, &release);
                for (int i = 0; i < 20; ++i) QCoreApplication::processEvents();
            }
        }
        // COMPOSITOR_GRAB_ACTION=<menu action objectName, e.g. filter.Vignette>: triggered as if chosen from the menu.
        if (!qEnvironmentVariable("COMPOSITOR_GRAB_ACTION").isEmpty()) {
            for (QAction *action : window.findChildren<QAction *>()) {
                if (action->objectName() != qEnvironmentVariable("COMPOSITOR_GRAB_ACTION")) continue;
                action->trigger();
                QElapsedTimer settle; settle.start();
                while (settle.elapsed() < 600) QCoreApplication::processEvents(QEventLoop::AllEvents, 20);
                break;
            }
        }
        // COMPOSITOR_GRAB_LAYER_DROP="source,row,fraction": a drag of the Layers list's row `source` dropped on row `row`
        // at `fraction` of its height (0 top, 0.5 middle — into a folder, 1 bottom), as the list's drop handler gets it.
        if (!qEnvironmentVariable("COMPOSITOR_GRAB_LAYER_DROP").isEmpty()) {
            const QStringList v = qEnvironmentVariable("COMPOSITOR_GRAB_LAYER_DROP").split(',');
            for (int i = 0; i < 10; ++i) QCoreApplication::processEvents();
            QWidget *content = nullptr;
            for (QWidget *w : window.findChildren<QWidget *>())
                if (w->acceptDrops() && w->property("listRow").isNull() && !w->findChildren<QWidget *>().isEmpty()
                    && std::any_of(w->children().cbegin(), w->children().cend(), [](QObject *c) { return c->property("listRow").isValid(); })) { content = w; break; }
            if (content && v.size() == 3) {
                QWidget *target = nullptr;
                for (QObject *c : content->children())
                    if (auto *w = qobject_cast<QWidget *>(c); w && w->property("listRow").toInt() == v[1].toInt() && w->property("listRow").isValid()) { target = w; break; }
                if (target) {
                    const QRect r = target->geometry();
                    const QPoint at(r.center().x(), r.top() + int(r.height() * v[2].toDouble()));
                    auto *mime = new QMimeData;
                    mime->setData("application/x-compositor-list-row", v[0].toUtf8());
                    QDragEnterEvent enter(at, Qt::MoveAction, mime, Qt::LeftButton, Qt::NoModifier);
                    QCoreApplication::sendEvent(content, &enter);
                    QDragMoveEvent move(at, Qt::MoveAction, mime, Qt::LeftButton, Qt::NoModifier);
                    QCoreApplication::sendEvent(content, &move);
                    QDropEvent drop(at, Qt::MoveAction, mime, Qt::LeftButton, Qt::NoModifier);
                    QCoreApplication::sendEvent(content, &drop);
                    QElapsedTimer settle; settle.start();
                    while (settle.elapsed() < 400) QCoreApplication::processEvents(QEventLoop::AllEvents, 20);
                }
            }
        }
        // COMPOSITOR_GRAB_REBIND="<shortcut title>,<key>": through the Keyboard Shortcuts editor as a user would — click
        // the shortcut's recorder, press the key, Save — then press the key on the canvas; prints the tool it selected.
        if (!qEnvironmentVariable("COMPOSITOR_GRAB_REBIND").isEmpty()) {
            const QStringList v = qEnvironmentVariable("COMPOSITOR_GRAB_REBIND").split(',');
            auto settle = [](int ms) { QElapsedTimer t; t.start(); while (t.elapsed() < ms) QCoreApplication::processEvents(QEventLoop::AllEvents, 20); };
            for (QAction *action : window.findChildren<QAction *>()) if (action->objectName() == "edit.shortcuts") action->trigger();
            settle(400);
            QDialog *editor = window.findChild<QDialog *>("floatingPanel.KeyboardShortcutsSheet");
            QPushButton *recorder = nullptr;
            if (editor && v.size() == 2) {
                for (QLabel *label : editor->findChildren<QLabel *>()) {
                    if (label->text() != v[0] || !label->parentWidget()) continue;
                    for (QPushButton *button : label->parentWidget()->findChildren<QPushButton *>()) { recorder = button; break; }
                    break;
                }
            }
            fprintf(stderr, "REBIND editor=%d recorder=%s\n", editor != nullptr, recorder ? qPrintable(recorder->text()) : "none");
            if (recorder) {
                recorder->setFocus(Qt::MouseFocusReason);   // as a real click does: the button takes focus from the search field
                recorder->click();
                settle(400);
                const QChar c = v[1].isEmpty() ? QChar('k') : v[1][0];
                QKeyEvent press(QEvent::KeyPress, int(c.toUpper().unicode()), Qt::NoModifier, QString(c));
                QCoreApplication::sendEvent(editor, &press);
                settle(400);
                editor = window.findChild<QDialog *>("floatingPanel.KeyboardShortcutsSheet");
                for (QPushButton *button : editor ? editor->findChildren<QPushButton *>() : QList<QPushButton *>())
                    if (button->text() == QLatin1String("Save")) { fprintf(stderr, "REBIND save enabled=%d\n", button->isEnabled()); button->click(); break; }
                settle(400);
                window.setTool(SessionWindow::Tool::Move);
                window.activateWindow();
                QKeyEvent key(QEvent::KeyPress, int(c.toUpper().unicode()), Qt::NoModifier, QString(c));
                QCoreApplication::sendEvent(&window, &key);
                settle(300);
                fprintf(stderr, "REBIND tool after '%s': %s\n", qPrintable(QString(c)), qPrintable(window.sessionState().value("tool").toString()));
            }
        }
        // COMPOSITOR_GRAB_LAYER_MENU=<row>: right-click that Layers-list row and capture its context menu as <path>.menu.png;
        // COMPOSITOR_GRAB_LAYER_CLICK="<row>,ctrl|shift": then click another row with that modifier (multi-select).
        auto layerRow = [&](int row) -> QWidget * {
            for (QWidget *w : window.findChildren<QWidget *>())
                if (w->property("listRow").isValid() && w->property("listRow").toInt() == row && w->parentWidget()
                    && !w->parentWidget()->property("listRow").isValid()) return w;
            return nullptr;
        };
        if (!qEnvironmentVariable("COMPOSITOR_GRAB_LAYER_MENU").isEmpty()) {
            for (int i = 0; i < 10; ++i) QCoreApplication::processEvents();
            if (QWidget *row = layerRow(qEnvironmentVariable("COMPOSITOR_GRAB_LAYER_MENU").toInt())) {
                QTimer::singleShot(300, [] {
                    if (auto *menu = qobject_cast<QMenu *>(QApplication::activePopupWidget())) {
                        menu->grab().save(qEnvironmentVariable("COMPOSITOR_GRAB_PATH") + ".menu.png");
                        menu->close();
                    }
                });
                QContextMenuEvent context(QContextMenuEvent::Mouse, QPoint(20, 10), row->mapToGlobal(QPoint(20, 10)));
                QCoreApplication::sendEvent(row, &context);
            }
        }
        if (!qEnvironmentVariable("COMPOSITOR_GRAB_LAYER_CLICK").isEmpty()) {
            const QStringList v = qEnvironmentVariable("COMPOSITOR_GRAB_LAYER_CLICK").split(',');
            for (int i = 0; i < 10; ++i) QCoreApplication::processEvents();
            if (QWidget *row = layerRow(v.value(0).toInt())) {
                const Qt::KeyboardModifiers mods = v.value(1) == "shift" ? Qt::ShiftModifier : Qt::ControlModifier;
                QMouseEvent release(QEvent::MouseButtonRelease, QPointF(60, 10), row->mapToGlobal(QPointF(60, 10)), Qt::LeftButton, Qt::NoButton, mods);
                QCoreApplication::sendEvent(row, &release);
                QElapsedTimer t; t.start(); while (t.elapsed() < 400) QCoreApplication::processEvents(QEventLoop::AllEvents, 20);
            }
        }
        if (!qEnvironmentVariable("COMPOSITOR_GRAB_STROKE").isEmpty()) {
            window.setTool(SessionWindow::Tool::Brush);
            window.paintStroke(200, 200, 600, 450);
        }
        if (!qEnvironmentVariable("COMPOSITOR_GRAB_MOUSE_STROKE").isEmpty()) {
            // Simulates mouse events for stroke testing - sets Brush and paints
            window.setTool(SessionWindow::Tool::Brush);
            window.paintStroke(100, 100, 500, 400);
        }
        // COMPOSITOR_BENCH=WxH (with COMPOSITOR_GRAB_PATH): interaction latency on a WxH document — per tool, hovering and dragging through the real
        // canvas widget with the event loop run after each event (the repaints it asked for included); prints ms per event.
        if (!qEnvironmentVariable("COMPOSITOR_BENCH").isEmpty()) {
            const QStringList size = qEnvironmentVariable("COMPOSITOR_BENCH").split(QLatin1Char('x'));
            const int bw = size.value(0).toInt() > 0 ? size.value(0).toInt() : 4000, bh = size.value(1).toInt() > 0 ? size.value(1).toInt() : 3000;
            window.resize(1440, 900);
            window.show();
            QWidget *canvas = window.findChild<QWidget *>(QStringLiteral("editorCanvas"));
            auto send = [&](QEvent::Type type, const QPointF &at, Qt::MouseButton button, Qt::MouseButtons buttons) {
                QMouseEvent e(type, at, canvas->mapToGlobal(at), button, buttons, Qt::NoModifier);
                QCoreApplication::sendEvent(canvas, &e);
            };
            auto flush = [&] { QCoreApplication::sendPostedEvents(); QCoreApplication::processEvents(QEventLoop::ExcludeUserInputEvents); };
            auto doc = [&](double fx, double fy) { return window.documentToCanvasPoint(QPointF(bw * fx, bh * fy)); };
            const std::pair<const char *, SessionWindow::Tool> tools[] = {
                {"move", SessionWindow::Tool::Move}, {"marquee", SessionWindow::Tool::Marquee},
                {"lasso", SessionWindow::Tool::Lasso}, {"brush", SessionWindow::Tool::Brush},
                {"hand", SessionWindow::Tool::Hand}, {"gradient", SessionWindow::Tool::Gradient}, {"zoom", SessionWindow::Tool::Zoom}};
            const int steps = 60;
            // COMPOSITOR_BENCH_TOOLS=brush,move: only those.
            const QStringList only = qEnvironmentVariable("COMPOSITOR_BENCH_TOOLS").split(QLatin1Char(','), Qt::SkipEmptyParts);
            for (const auto &[name, tool] : tools) {
                if (!only.isEmpty() && !only.contains(QLatin1String(name))) continue;
                window.sendCommand({{"version", 1}, {"action", "new"}, {"width", bw}, {"height", bh}, {"emptyLayer", true}});
                QElapsedTimer settleNew; settleNew.start();   // the main pump picks up the new document
                while (settleNew.elapsed() < 300) QCoreApplication::processEvents(QEventLoop::AllEvents, 20);
                // COMPOSITOR_BENCH_LAYERS=N: N more layers, each crossed by a wide opaque stroke (a document with content).
                for (int layer = 0; layer < qEnvironmentVariable("COMPOSITOR_BENCH_LAYERS").toInt(); ++layer) {
                    window.sendCommand({{"version", 1}, {"action", "addLayer"}});
                    const QJsonObject brush{{"diameter", 300.0}, {"hardness", 0.8}, {"opacity", 1.0}, {"red", 0.2 + 0.1 * (layer % 7)},
                                            {"green", 0.5}, {"blue", 0.9 - 0.1 * (layer % 7)}, {"erasing", 0}, {"mask", 0}};
                    window.sendCommand({{"version", 1}, {"action", "brushBegin"}, {"x", bw * 0.1}, {"y", bh * (0.1 + 0.08 * layer)}, {"parameters", brush}});
                    window.sendCommand({{"version", 1}, {"action", "brushMove"}, {"x", bw * 0.9}, {"y", bh * (0.2 + 0.08 * layer)}});
                    window.sendCommand({{"version", 1}, {"action", "brushEnd"}});
                }
                if (qEnvironmentVariableIsSet("COMPOSITOR_BENCH_LAYERS")) {
                    QElapsedTimer settleLayers; settleLayers.start();
                    while (settleLayers.elapsed() < 1500) QCoreApplication::processEvents(QEventLoop::AllEvents, 20);
                }
                window.setTool(tool);
                // COMPOSITOR_BENCH_DIAMETER: the brush size the painting tools use.
                if (qEnvironmentVariableIsSet("COMPOSITOR_BENCH_DIAMETER"))
                    window.sendCommand({{"version", 1}, {"action", "setBrushSettings"},
                                        {"parameters", QJsonObject{{"diameter", qEnvironmentVariable("COMPOSITOR_BENCH_DIAMETER").toDouble()}}}});
                for (int i = 0; i < 10; ++i) QCoreApplication::processEvents();
                QElapsedTimer t; t.start();
                for (int i = 0; i < steps; ++i) {
                    send(QEvent::MouseMove, doc(0.3 + 0.4 * i / steps, 0.5), Qt::NoButton, Qt::NoButton);
                    flush();
                }
                const double hover = t.nsecsElapsed() / 1e6 / steps;
                t.restart();
                send(QEvent::MouseButtonPress, doc(0.3, 0.3), Qt::LeftButton, Qt::LeftButton);
                flush();
                const double press = t.nsecsElapsed() / 1e6;
                t.restart();
                // COMPOSITOR_BENCH_EVENTS=N: N pointer moves arrive per frame (a 1000 Hz mouse at 60 fps is ~16); the
                // figure is then milliseconds per frame.
                const int perFrame = std::max(1, qEnvironmentVariable("COMPOSITOR_BENCH_EVENTS").toInt());
                for (int i = 1; i <= steps; ++i) {
                    for (int k = 0; k < perFrame; ++k) {
                        const double f = (i - 1 + (k + 1.0) / perFrame) / steps;
                        send(QEvent::MouseMove, doc(0.3 + 0.3 * f, 0.3 + 0.2 * f), Qt::NoButton, Qt::LeftButton);
                    }
                    flush();
                }
                const double drag = t.nsecsElapsed() / 1e6 / steps;

                t.restart();
                send(QEvent::MouseButtonRelease, doc(0.6, 0.5), Qt::LeftButton, Qt::NoButton);
                flush();
                const double release = t.nsecsElapsed() / 1e6;
                t.restart();
                for (int i = 0; i < 10; ++i) QCoreApplication::processEvents();
                const double settle = t.nsecsElapsed() / 1e6;
                std::fprintf(stderr, "BENCH %-9s hover %6.2f ms  press %7.2f ms  drag %6.2f ms  release %7.2f ms  settle %7.2f ms\n",
                             name, hover, press, drag, release, settle);
            }
            return 0;
        }
        // COMPOSITOR_GRAB_PINCH=<magnification>[,steps]: a trackpad pinch over the canvas centre, as the touchpad sends it.
        if (!qEnvironmentVariable("COMPOSITOR_GRAB_PINCH").isEmpty()) {
            const QStringList v = qEnvironmentVariable("COMPOSITOR_GRAB_PINCH").split(QLatin1Char(','));
            if (QWidget *canvas = window.findChild<QWidget *>(QStringLiteral("editorCanvas"))) {
                window.show();
                for (int i = 0; i < 10; ++i) QCoreApplication::processEvents();
                const QPointF centre(canvas->width() / 2.0, canvas->height() / 2.0);
                for (int step = 0; step < std::max(1, v.value(1).toInt()); ++step) {
                    QNativeGestureEvent pinch(Qt::ZoomNativeGesture, QPointingDevice::primaryPointingDevice(), 2, centre,
                                              canvas->mapTo(&window, centre), canvas->mapToGlobal(centre), v.value(0).toDouble(),
                                              QPointF(), 0);
                    QCoreApplication::sendEvent(canvas, &pinch);
                }
                for (int i = 0; i < 10; ++i) QCoreApplication::processEvents();
            }
        }
        // COMPOSITOR_GRAB_WAIT_MS=<ms>: let background work the menu items started (a subject model's inference) finish.
        if (qEnvironmentVariableIsSet("COMPOSITOR_GRAB_WAIT_MS")) {
            QElapsedTimer wait; wait.start();
            while (wait.elapsed() < qEnvironmentVariable("COMPOSITOR_GRAB_WAIT_MS").toInt())
                QCoreApplication::processEvents(QEventLoop::AllEvents, 20);
        }
        // COMPOSITOR_GRAB_HOVER_PANELS=<count>: the pointer resting on, then moving over, every hover-tracked view in the
        // docked panels (label scrubbing), as a mouse would — each hovered view's handler runs.
        if (qEnvironmentVariableIsSet("COMPOSITOR_GRAB_HOVER_PANELS")) {
            window.show();
            const int rounds = std::max(1, qEnvironmentVariable("COMPOSITOR_GRAB_HOVER_PANELS").toInt());
            int sent = 0;
            QElapsedTimer spent; spent.start();
            for (int round = 0; round < rounds; ++round) {
                for (QWidget *w : window.findChildren<QWidget *>()) {
                    if (!w->testAttribute(Qt::WA_Hover) || !w->isVisible() || !w->property("swiftUIHandle").isNull()) continue;
                    const QPointF at(w->width() / 2.0 + round % 3, w->height() / 2.0);
                    // The pointer really is there: a view rebuilt under it gets Qt's own hover-enter, as on screen.
                    QCursor::setPos(w->mapToGlobal(at.toPoint()));
                    QHoverEvent enter(round == 0 ? QEvent::HoverEnter : QEvent::HoverMove, at, w->mapToGlobal(at), QPointF(-1, -1));
                    QCoreApplication::sendEvent(w, &enter);
                    ++sent;
                }
                for (int i = 0; i < 5; ++i) QCoreApplication::processEvents();
            }
            std::fprintf(stderr, "HOVER sent=%d rounds=%d in %lld ms\n", sent, rounds, (long long)spent.elapsed());
        }
        // COMPOSITOR_GRAB_LAYER_POINT="row,fraction[,alt|ctrl|shift]": a click in that row of the layers list, `fraction`
        // of the way down it (0 top ... 1 bottom), with those keys held — on whatever view is there, as a mouse would.
        if (!qEnvironmentVariable("COMPOSITOR_GRAB_LAYER_POINT").isEmpty()) {
            const QStringList v = qEnvironmentVariable("COMPOSITOR_GRAB_LAYER_POINT").split(QLatin1Char(','));
            window.show();
            for (int i = 0; i < 10; ++i) QCoreApplication::processEvents();
            QWidget *row = nullptr;
            for (QWidget *w : window.findChildren<QWidget *>())
                if (w->isVisible() && w->property("listRow").isValid() && w->property("listRow").toInt() == v.value(0).toInt()
                    && !(w->parentWidget() && w->parentWidget()->property("listRow").isValid())) { row = w; break; }
            if (row) {
                Qt::KeyboardModifiers modifiers;
                if (v.contains(QStringLiteral("alt"))) modifiers |= Qt::AltModifier;
                if (v.contains(QStringLiteral("ctrl"))) modifiers |= Qt::ControlModifier;
                if (v.contains(QStringLiteral("shift"))) modifiers |= Qt::ShiftModifier;
                int x = 120;   // "x=<points>" among the values picks another spot along the row
                for (const QString &part : v) if (part.startsWith(QStringLiteral("x="))) x = part.mid(2).toInt();
                const QPoint at(std::min(row->width() - 1, x), std::min(row->height() - 1, int(row->height() * v.value(1).toDouble())));
                // Whatever is on top at that point, as the mouse would find it (an overlay above the row's content).
                const QPoint inWindow = row->mapTo(&window, at);
                QPointer<QWidget> target = window.childAt(inWindow) ? window.childAt(inWindow) : row;
                const QPoint local = target->mapFrom(&window, inWindow);
                const QPoint global = target->mapToGlobal(local);
                std::fprintf(stderr, "LAYERPOINT row %d at %d,%d -> %s tap=%d %d,%d %dx%d\n", v.value(0).toInt(), at.x(), at.y(), target->metaObject()->className(), target->property("swiftuiTapGestureCount").toInt(), target->x(), target->y(), target->width(), target->height());
                QMouseEvent press(QEvent::MouseButtonPress, local, global, Qt::LeftButton, Qt::LeftButton, modifiers);
                QCoreApplication::sendEvent(target, &press);
                if (target) {   // the press may have rebuilt the panel
                    QMouseEvent release(QEvent::MouseButtonRelease, local, global, Qt::LeftButton, Qt::NoButton, modifiers);
                    QCoreApplication::sendEvent(target, &release);
                }
                for (int i = 0; i < 20; ++i) QCoreApplication::processEvents();
            } else std::fprintf(stderr, "LAYERPOINT no row %d\n", v.value(0).toInt());
        }
        // COMPOSITOR_GRAB_EFFECT_DROP=<row>: the first effect row in the list, dropped on that row as an Option-drag ends
        // (the drop half of the gesture; a real QDrag needs a window system).
        if (!qEnvironmentVariable("COMPOSITOR_GRAB_EFFECT_DROP").isEmpty()) {
            for (int i = 0; i < 10; ++i) QCoreApplication::processEvents();
            QString source;
            for (QWidget *w : window.findChildren<QWidget *>())
                if (w->isVisible() && w->objectName().startsWith(QStringLiteral("layerEffectRow:"))) { source = w->objectName().mid(15); break; }
            QWidget *row = nullptr;
            const int target = qEnvironmentVariable("COMPOSITOR_GRAB_EFFECT_DROP").toInt();
            for (QWidget *w : window.findChildren<QWidget *>())
                if (w->isVisible() && w->property("listRow").isValid() && w->property("listRow").toInt() == target
                    && !(w->parentWidget() && w->parentWidget()->property("listRow").isValid())) { row = w; break; }
            if (row && !source.isEmpty()) {
                QWidget *content = row->parentWidget();
                while (content && !content->acceptDrops()) content = content->parentWidget();
                const QPointF at = content->mapFrom(row, QPoint(row->width() / 2, row->height() / 2));
                auto *mime = new QMimeData;
                mime->setData("com.compositor.layer-effect", source.toUtf8());
                QDragEnterEvent enter(at.toPoint(), Qt::CopyAction, mime, Qt::LeftButton, Qt::AltModifier);
                QCoreApplication::sendEvent(content, &enter);
                QDropEvent drop(at, Qt::CopyAction, mime, Qt::LeftButton, Qt::AltModifier);
                QCoreApplication::sendEvent(content, &drop);
                for (int i = 0; i < 20; ++i) QCoreApplication::processEvents();
                std::fprintf(stderr, "EFFECTDROP %s on row %d accepted=%d\n", qPrintable(source), target, drop.isAccepted());
            } else {
                std::fprintf(stderr, "EFFECTDROP nothing to drop (source '%s')\n", qPrintable(source));
                for (QWidget *w : window.findChildren<QWidget *>())
                    if (w->property("listRow").isValid() && !(w->parentWidget() && w->parentWidget()->property("listRow").isValid()))
                        std::fprintf(stderr, "EFFECTDROP row %d visible %d %dx%d\n", w->property("listRow").toInt(), w->isVisible(), w->width(), w->height());
            }
        }
        // COMPOSITOR_GRAB_CLIPBOARD_REPORT=1: what the desktop clipboard holds now (after the menu items above).
        if (qEnvironmentVariableIsSet("COMPOSITOR_GRAB_CLIPBOARD_REPORT")) {
            const QMimeData *mime = QApplication::clipboard()->mimeData();
            const QImage image = QApplication::clipboard()->image();
            std::fprintf(stderr, "CLIPBOARD formats=%s image=%dx%d\n", mime ? qPrintable(mime->formats().join(',')) : "-",
                         image.width(), image.height());
        }
        // COMPOSITOR_GRAB_DRAG="x0,y0,x1,y1" (document pixels): a real press / moves / release on the canvas widget with
        // the current tool; COMPOSITOR_GRAB_KEY=return|escape then presses that key (e.g. to apply a gradient).
        if (!qEnvironmentVariable("COMPOSITOR_GRAB_DRAG").isEmpty()) {
            const QStringList v = qEnvironmentVariable("COMPOSITOR_GRAB_DRAG").split(',');
            QWidget *canvas = window.findChild<QWidget *>(QStringLiteral("editorCanvas"));
            if (v.size() == 4 && canvas) {
                window.show();
                for (int i = 0; i < 10; ++i) QCoreApplication::processEvents();
                const QPointF from = window.documentToCanvasPoint(QPointF(v[0].toDouble(), v[1].toDouble()));
                const QPointF to = window.documentToCanvasPoint(QPointF(v[2].toDouble(), v[3].toDouble()));
                auto send = [&](QEvent::Type type, const QPointF &at, Qt::MouseButtons buttons) {
                    // COMPOSITOR_GRAB_DRAG_MODIFIERS=ctrl|shift|ctrl+shift held through the drag (e.g. Ctrl distorts).
                    const QString mods = qEnvironmentVariable("COMPOSITOR_GRAB_DRAG_MODIFIERS");
                    Qt::KeyboardModifiers modifiers = Qt::NoModifier;
                    if (mods.contains(QLatin1String("ctrl"))) modifiers |= Qt::ControlModifier;
                    if (mods.contains(QLatin1String("shift"))) modifiers |= Qt::ShiftModifier;
                    QMouseEvent e(type, at, canvas->mapToGlobal(at), Qt::LeftButton, buttons, modifiers);
                    QCoreApplication::sendEvent(canvas, &e);
                };
                send(QEvent::MouseButtonPress, from, Qt::LeftButton);
                for (int step = 1; step <= 8; ++step) {
                    send(QEvent::MouseMove, from + (to - from) * (step / 8.0), Qt::LeftButton);
                    for (int i = 0; i < 3; ++i) QCoreApplication::processEvents();
                }
                // COMPOSITOR_GRAB_DRAG_HOLD=1: the button stays down — the picture shows the drag in progress.
                if (qEnvironmentVariableIsSet("COMPOSITOR_GRAB_DRAG_HOLD")) {
                    QElapsedTimer frame; frame.start();
                    while (frame.elapsed() < 150) QCoreApplication::processEvents(QEventLoop::AllEvents, 20);
                } else {
                    send(QEvent::MouseButtonRelease, to, Qt::NoButton);
                }
                for (int i = 0; i < 10; ++i) QCoreApplication::processEvents();
                // COMPOSITOR_GRAB_TYPE: typed into whatever has focus (the Type tool's inline editor).
                const QString typed = qEnvironmentVariable("COMPOSITOR_GRAB_TYPE");
                for (const QChar c : typed) {
                    QWidget *target = QApplication::focusWidget() ? QApplication::focusWidget() : &window;
                    QKeyEvent press(QEvent::KeyPress, 0, Qt::NoModifier, QString(c));
                    QCoreApplication::sendEvent(target, &press);
                    for (int i = 0; i < 2; ++i) QCoreApplication::processEvents();
                }
                const QString key = qEnvironmentVariable("COMPOSITOR_GRAB_KEY");
                if (!key.isEmpty()) {
                    QWidget *target = key == "ctrlreturn" && QApplication::focusWidget() ? QApplication::focusWidget() : static_cast<QWidget *>(&window);
                    QKeyEvent press(QEvent::KeyPress, key == "escape" ? Qt::Key_Escape : Qt::Key_Return,
                                    key == "ctrlreturn" ? Qt::ControlModifier : Qt::NoModifier);
                    QCoreApplication::sendEvent(target, &press);
                    for (int i = 0; i < 10; ++i) QCoreApplication::processEvents();
                }
                const QJsonObject st = window.sessionState();
                QStringList names;
                for (const auto &l : st.value("layers").toArray()) names << l.toObject().value("name").toString();
                fprintf(stderr, "Drag result: layers=[%s] undo=%s gradientPending=%d\n", qPrintable(names.join(",")),
                        qPrintable(st.value("undoName").toString()), st.value("gradientLine").isArray() ? 1 : 0);
            }
        }
        if (!qEnvironmentVariable("COMPOSITOR_TEST_TOOL_RAIL_CLICK").isEmpty()) {
            auto buttons = window.findChildren<QPushButton *>();
            qDebug() << "Total buttons in window:" << buttons.size();
            for (auto *b : buttons) {
                if (b->accessibleName().contains("Brush") || b->toolTip().contains("Brush")) {
                    qDebug() << "FOUND BRUSH BUTTON:" << b << "calling click()";
                    b->click();
                }
            }
            for (int i = 0; i < 10; ++i) QCoreApplication::processEvents();
            qDebug() << "After click, window.currentTool() =" << static_cast<int>(window.currentTool());
            qDebug() << "After click, sessionState tool =" << window.sessionState().value("tool").toString();
        }
        for (int i = 0; i < 10; ++i) {
            QCoreApplication::processEvents();
        }
        window.grab().save(qEnvironmentVariable("COMPOSITOR_GRAB_PATH"));
        // Upstream's floating panels (tool windows) beside it: <path>.<panel>.png.
        for (QDialog *panel : window.findChildren<QDialog *>())
            if (panel->isVisible() && panel->objectName().startsWith(QLatin1String("floatingPanel.")))
                panel->grab().save(qEnvironmentVariable("COMPOSITOR_GRAB_PATH") + "." + panel->objectName().mid(14) + ".png");
        // COMPOSITOR_GRAB_SWIFTUI_TREE=<panel name, e.g. NavigationToolHeader> renders that panel standalone
        // through the generic SwiftUI-compat -> Qt renderer (SwiftUIQtRenderer.cpp) and captures it as
        // <path>.swiftui.png — the screenshot-diff proof point for the "Generic SwiftUI→Qt compat runtime" plan.
        // Deliberately does not touch SessionWindow's own hand-built toolbar/panels.
        const QString swiftUIPanel = qEnvironmentVariable("COMPOSITOR_GRAB_SWIFTUI_TREE");
        if (!swiftUIPanel.isEmpty()) {
            if (QWidget *rendered = swiftUIRenderPanel(window.sessionHandle(), swiftUIPanel)) {
                rendered->resize(qMax(rendered->sizeHint().width(), 900), qMax(rendered->sizeHint().height(), 60));
                rendered->show();
                for (int i = 0; i < 10; ++i) QCoreApplication::processEvents();
                rendered->grab().save(qEnvironmentVariable("COMPOSITOR_GRAB_PATH") + ".swiftui.png");
                delete rendered;
            }
            return 0;
        }
        // COMPOSITOR_GRAB_DIALOG=<Adjust kind | ColorPicker> also captures that dialog as <path>.dialog.png.
        const QString dialogKind = qEnvironmentVariable("COMPOSITOR_GRAB_DIALOG");
        if (!dialogKind.isEmpty()) {
            QDialog *dialog = nullptr;
            if (dialogKind == "AdjustmentsPanel") {
                if (auto *dock = window.findChild<QDockWidget *>("dock.adjustments")) {
                    dock->show();
                    for (int i = 0; i < 10; ++i) QCoreApplication::processEvents();
                    dock->grab().save(qEnvironmentVariable("COMPOSITOR_GRAB_PATH") + ".dialog.png");
                }
                return 0;
            }
            if (dialogKind == "ColorPicker") {
                dialog = new ColorPickerDialog(QColor(0xFA, 0x75, 0x27), QStringLiteral("Color Picker (Foreground Color)"), &window);
            } else {
                AdjustServices services;
                services.histogram = [](int) {
                    std::vector<double> bins(256);
                    for (int i = 0; i < 256; ++i) bins[i] = 40.0 * std::exp(-std::pow((i - 60) / 40.0, 2)) + 15.0 * std::exp(-std::pow((i - 170) / 60.0, 2)) + (i < 6 ? 60 : 1);
                    return bins;
                };
                services.requestSample = [](std::function<void(const QColor &)>) {};
                dialog = new AdjustDialog(dialogKind, [](const QJsonObject &) { return true; }, &window, services);
            }
            dialog->show();
            for (int i = 0; i < 10; ++i) QCoreApplication::processEvents();
            dialog->grab().save(qEnvironmentVariable("COMPOSITOR_GRAB_PATH") + ".dialog.png");
        }
        const QString menuName = qEnvironmentVariable("COMPOSITOR_GRAB_MENU");
        if (!menuName.isEmpty() && window.menuBar()) {
            for (auto *act : window.menuBar()->actions()) {
                if (act->isVisible() && act->text().contains(menuName, Qt::CaseInsensitive) && act->menu()) {
                    auto *menu = act->menu();
                    menu->show();
                    for (int i = 0; i < 10; ++i) QCoreApplication::processEvents();
                    menu->grab().save(qEnvironmentVariable("COMPOSITOR_GRAB_PATH") + ".menu.png");
                    for (auto *subAct : menu->actions()) {
                        if (subAct->menu()) {
                            auto *subMenu = subAct->menu();
                            subMenu->show();
                            for (int i = 0; i < 10; ++i) QCoreApplication::processEvents();
                            subMenu->grab().save(qEnvironmentVariable("COMPOSITOR_GRAB_PATH") + ".submenu.png");
                            break;
                        }
                    }
                    break;
                }
            }
            return 0;
        }
        return 0;
    }
    if (qEnvironmentVariable("QT_QPA_PLATFORM") == "offscreen") {
        QCoreApplication::processEvents();
        return 0;
    }
    return app.exec();
}

extern "C" int compositor_qt_imageio_selftest(void);

extern "C" int compositor_host_io_smoke(int argc, char **argv) {
    QApplication app(argc, argv);
    compositor_qt_imageio_install();
    compositor_raw_install();   // camera RAW via LibRaw (a no-op when built without it)
    if (compositor_qt_imageio_selftest() != 0) return 8;
    QTemporaryDir temporary;
    if (!temporary.isValid()) return 1;
    SessionWindow window;
    const QString root = temporary.path();
    if (!window.exportPNG(root + "/export.png") || !QFile::exists(root + "/export.png")) return 2;
    if (!window.exportJPEG(root + "/export.jpg", 90) || !QFile::exists(root + "/export.jpg")) return 3;
    if (!window.saveProject(root + "/project")) return 4;
    if (!QFile::exists(root + "/project/manifest.json") ||
        QDir(root + "/project/images").entryList(QDir::Files).isEmpty()) return 5;
    if (!window.loadProject(root + "/project")) return 6;
    return 0;
}
