// host_run.cpp — the Qt host entry called by the Swift composition root.
//
// The Linux port's composition root is inverted: a Swift `@main`
// (Sources/CompositorHostBootstrap/hostMain.swift) bootstraps the Swift runtime
// + Foundation (which a C++ main cannot on the Freedesktop Swift 6.3 SDK), then
// calls this `compositor_host_run` C entry to run the Qt Widgets shell. The Qt
// host in turn calls back into the Swift core through the `compositor_session_*`
// C ABI (ENG-1). This is the only entry point — there is no separate C++-main
// build path.
//
// This entry creates the real `SessionWindow` (host/SessionWindow.h, Q_OBJECT).
// Its moc output (host/moc_SessionWindow.cpp) is generated by `moc` and committed
// so SwiftPM can build it without AUTOMOC. The Flatpak build rebuilds the same
// window via CMake/AUTOMOC; this SwiftPM path proves the moc'd-Qt -> Swift-@main
// link. The headless proof processes pending paint events without entering the
// blocking event loop; the Flatpak app calls app.exec() here.

#include <QApplication>
#include <QCoreApplication>
#include <QProcessEnvironment>
#include <QTemporaryDir>
#include <QFile>
#include <QDir>

#include "compositor_host_run.h"
#include "EditorDialogs.h"
#include "ColorPickerDialog.h"
#include "SwiftUIQtRenderer.h"
#include <cmath>
#include <QDockWidget>
#include <QMenuBar>
#include <QMenu>
#include <vector>
#include <QIcon>
#include <QStyleFactory>
#include "SessionWindow.h"

#if defined(COMPOSITOR_SKIA_BRIDGE)
#include "SkiaBridge.h"
#endif

extern "C" int compositor_qt_imageio_install(void);

extern "C" int compositor_host_run(int argc, char **argv) {
    QApplication app(argc, argv);
    app.setStyle(QStyleFactory::create(QStringLiteral("Fusion")));
    // Qt image plugins become the ImageIO compat backend (JPEG/TIFF/WebP/... beyond the portable PNG codec).
    compositor_qt_imageio_install();
    app.setApplicationName("Compositor");
    app.setOrganizationName("Compositor");
    app.setDesktopFileName("com.wonderassembly.Compositor");

    QIcon appIcon;
    const int iconSizes[] = {16, 32, 64, 128, 256, 512, 1024};
    for (int s : iconSizes) {
        const QString p1 = QStringLiteral("Compositor/Assets.xcassets/AppIcon.appiconset/app-icon-%1.png").arg(s);
        if (QFile::exists(p1)) {
            appIcon.addFile(p1);
        } else {
            const QString p2 = QDir::homePath() + QStringLiteral("/.local/share/icons/hicolor/%1x%1/apps/com.wonderassembly.Compositor.png").arg(s);
            if (QFile::exists(p2)) appIcon.addFile(p2);
        }
    }
    if (!appIcon.isNull()) {
        app.setWindowIcon(appIcon);
    }

#if defined(COMPOSITOR_SKIA_BRIDGE)
    // Plan §6 startup: try Vulkan, fall back to Raster. The renderer backs
    // the Swift CGContextCompat shim; on any failure the Swift
    // DocumentRenderer remains the ultimate fallback.
    CompRendererKind kind = COMP_RENDERER_RASTER;
    CompRenderer *renderer = compositor_renderer_create(0, &kind);
    if (renderer) compositor_renderer_activate(renderer);
#endif
    // SessionWindow (moc'd Q_OBJECT) drives the Swift core via compositor_session_*
    // and paints the composited RGBA — the architecture the Flatpak build ships.
    SessionWindow window;
    if (!appIcon.isNull()) {
        window.setWindowIcon(appIcon);
    }
    for (int i = 1; i < argc; ++i) {
        if (!argv[i]) continue;
        QString arg = QString::fromLocal8Bit(argv[i]);
        if (arg.startsWith(QLatin1Char('-'))) continue;
        if (QFile::exists(arg)) {
            if (arg.endsWith(QStringLiteral(".cproject"), Qt::CaseInsensitive)) {
                window.loadProject(arg);
            } else {
                window.importImage(arg);
            }
            break;
        }
    }
    window.show();
    if (!qEnvironmentVariable("COMPOSITOR_GRAB_PATH").isEmpty()) {
        const QString toolArg = qEnvironmentVariable("COMPOSITOR_GRAB_TOOL");
        if (toolArg == "move") window.setTool(SessionWindow::Tool::Move);
        else if (toolArg == "brush") window.setTool(SessionWindow::Tool::Brush);
        else if (toolArg == "crop") window.setTool(SessionWindow::Tool::Crop);
        else if (toolArg == "zoom") window.setTool(SessionWindow::Tool::Zoom);
        else if (toolArg == "lasso") window.setTool(SessionWindow::Tool::Lasso);
        else if (toolArg == "marquee") window.setTool(SessionWindow::Tool::Marquee);
        else if (toolArg == "gradient") window.setTool(SessionWindow::Tool::Gradient);
        else if (toolArg == "shape") window.setTool(SessionWindow::Tool::Shape);
        else if (toolArg == "type") window.setTool(SessionWindow::Tool::Type);
        else if (toolArg == "spotHealing") window.setTool(SessionWindow::Tool::SpotHealing);
        else if (toolArg == "cloneStamp") window.setTool(SessionWindow::Tool::CloneStamp);
        if (!qEnvironmentVariable("COMPOSITOR_GRAB_SELECTION_MODE").isEmpty()) {
            const QString mode = qEnvironmentVariable("COMPOSITOR_GRAB_SELECTION_MODE");
            QJsonObject cmd;
            cmd["version"] = 1;
            cmd["action"] = "setSelectionMode";
            cmd["kind"] = mode;
            window.sendCommand(cmd);
            window.updateOptionsBar();
        }
        if (!qEnvironmentVariable("COMPOSITOR_GRAB_STROKE").isEmpty()) {
            window.setTool(SessionWindow::Tool::Brush);
            window.paintStroke(200, 200, 600, 450);
        }
        if (!qEnvironmentVariable("COMPOSITOR_GRAB_MOUSE_STROKE").isEmpty()) {
            // Simulates mouse events for stroke testing - sets Brush and paints
            window.setTool(SessionWindow::Tool::Brush);
            window.paintStroke(100, 100, 500, 400);
        }
        if (!qEnvironmentVariable("COMPOSITOR_TEST_TOOL_RAIL_CLICK").isEmpty()) {
            auto buttons = window.findChildren<QPushButton *>();
            qDebug() << "Total buttons in window:" << buttons.size();
            for (auto *b : buttons) {
                if (b->accessibleName().contains("Brush") || b->toolTip().contains("Brush")) {
                    qDebug() << "FOUND BRUSH BUTTON:" << b << "calling click()";
                    b->click();
                }
            }
            for (int i = 0; i < 10; ++i) QCoreApplication::processEvents();
            qDebug() << "After click, window.currentTool() =" << static_cast<int>(window.currentTool());
            qDebug() << "After click, sessionState tool =" << window.sessionState().value("tool").toString();
        }
        for (int i = 0; i < 10; ++i) {
            QCoreApplication::processEvents();
        }
        window.grab().save(qEnvironmentVariable("COMPOSITOR_GRAB_PATH"));
        // COMPOSITOR_GRAB_SWIFTUI_TREE=<panel name, e.g. NavigationToolHeader> renders that panel standalone
        // through the generic SwiftUI-compat -> Qt renderer (SwiftUIQtRenderer.cpp) and captures it as
        // <path>.swiftui.png — the screenshot-diff proof point for the "Generic SwiftUI→Qt compat runtime" plan.
        // Deliberately does not touch SessionWindow's own hand-built toolbar/panels.
        const QString swiftUIPanel = qEnvironmentVariable("COMPOSITOR_GRAB_SWIFTUI_TREE");
        if (!swiftUIPanel.isEmpty()) {
            if (QWidget *rendered = swiftUIRenderPanel(window.sessionHandle(), swiftUIPanel)) {
                rendered->resize(qMax(rendered->sizeHint().width(), 900), qMax(rendered->sizeHint().height(), 60));
                rendered->show();
                for (int i = 0; i < 10; ++i) QCoreApplication::processEvents();
                rendered->grab().save(qEnvironmentVariable("COMPOSITOR_GRAB_PATH") + ".swiftui.png");
                delete rendered;
            }
            return 0;
        }
        // COMPOSITOR_GRAB_DIALOG=<Adjust kind | ColorPicker> also captures that dialog as <path>.dialog.png.
        const QString dialogKind = qEnvironmentVariable("COMPOSITOR_GRAB_DIALOG");
        if (!dialogKind.isEmpty()) {
            QDialog *dialog = nullptr;
            if (dialogKind == "AdjustmentsPanel") {
                if (auto *dock = window.findChild<QDockWidget *>("dock.adjustments")) {
                    dock->show();
                    for (int i = 0; i < 10; ++i) QCoreApplication::processEvents();
                    dock->grab().save(qEnvironmentVariable("COMPOSITOR_GRAB_PATH") + ".dialog.png");
                }
                return 0;
            }
            if (dialogKind == "ColorPicker") {
                dialog = new ColorPickerDialog(QColor(0xFA, 0x75, 0x27), QStringLiteral("Color Picker (Foreground Color)"), &window);
            } else {
                AdjustServices services;
                services.histogram = [](int) {
                    std::vector<double> bins(256);
                    for (int i = 0; i < 256; ++i) bins[i] = 40.0 * std::exp(-std::pow((i - 60) / 40.0, 2)) + 15.0 * std::exp(-std::pow((i - 170) / 60.0, 2)) + (i < 6 ? 60 : 1);
                    return bins;
                };
                services.requestSample = [](std::function<void(const QColor &)>) {};
                dialog = new AdjustDialog(dialogKind, [](const QJsonObject &) { return true; }, &window, services);
            }
            dialog->show();
            for (int i = 0; i < 10; ++i) QCoreApplication::processEvents();
            dialog->grab().save(qEnvironmentVariable("COMPOSITOR_GRAB_PATH") + ".dialog.png");
        }
        const QString menuName = qEnvironmentVariable("COMPOSITOR_GRAB_MENU");
        if (!menuName.isEmpty() && window.menuBar()) {
            for (auto *act : window.menuBar()->actions()) {
                if (act->text().contains(menuName, Qt::CaseInsensitive) && act->menu()) {
                    auto *menu = act->menu();
                    menu->show();
                    for (int i = 0; i < 10; ++i) QCoreApplication::processEvents();
                    menu->grab().save(qEnvironmentVariable("COMPOSITOR_GRAB_PATH") + ".menu.png");
                    for (auto *subAct : menu->actions()) {
                        if (subAct->menu()) {
                            auto *subMenu = subAct->menu();
                            subMenu->show();
                            for (int i = 0; i < 10; ++i) QCoreApplication::processEvents();
                            subMenu->grab().save(qEnvironmentVariable("COMPOSITOR_GRAB_PATH") + ".submenu.png");
                            break;
                        }
                    }
                    break;
                }
            }
            return 0;
        }
        return 0;
    }
    if (qEnvironmentVariable("QT_QPA_PLATFORM") == "offscreen") {
        QCoreApplication::processEvents();
        return 0;
    }
    class QuitEventFilter : public QObject {
    public:
        explicit QuitEventFilter(QObject *parent = nullptr) : QObject(parent) {}
    protected:
        bool eventFilter(QObject *obj, QEvent *event) override {
            if (event->type() == QEvent::Quit) {
                fprintf(stderr, ">>> RECEIVED QEvent::Quit on %s (spontaneous=%d)\n",
                        obj->metaObject()->className(), (int)event->spontaneous());
            } else if (event->type() == QEvent::Close) {
                fprintf(stderr, ">>> RECEIVED QEvent::Close on %s (spontaneous=%d)\n",
                        obj->metaObject()->className(), (int)event->spontaneous());
            }
            return QObject::eventFilter(obj, event);
        }
    };
    QuitEventFilter quitFilter(&app);
    app.installEventFilter(&quitFilter);

    int ret = app.exec();
    fprintf(stderr, ">>> app.exec() returned %d\n", ret);
    return ret;
}

extern "C" int compositor_qt_imageio_selftest(void);

extern "C" int compositor_host_io_smoke(int argc, char **argv) {
    QApplication app(argc, argv);
    compositor_qt_imageio_install();
    if (compositor_qt_imageio_selftest() != 0) return 8;
    QTemporaryDir temporary;
    if (!temporary.isValid()) return 1;
    SessionWindow window;
    const QString root = temporary.path();
    if (!window.exportPNG(root + "/export.png") || !QFile::exists(root + "/export.png")) return 2;
    if (!window.exportJPEG(root + "/export.jpg", 90) || !QFile::exists(root + "/export.jpg")) return 3;
    if (!window.saveProject(root + "/project")) return 4;
    if (!QFile::exists(root + "/project/manifest.json") ||
        QDir(root + "/project/images").entryList(QDir::Files).isEmpty()) return 5;
    if (!window.loadProject(root + "/project")) return 6;
    return 0;
}
