#!/usr/bin/env bash
# Regenerates Sources/Overrides/CompositorApp.swift from upstream's Compositor/CompositorApp.swift. The only changes
# include the Color Range menu from pinned upstream 1.3.4 and these mechanical adaptations: `#selector(Type.method(_:))` becomes `Selector(("method:"))` (Linux Swift has no Objective-C
# runtime, so `#selector` cannot compile), and `@main` goes (the Linux entry point is CompositorHostBootstrap; the
# shell reads the app's `.commands` to build its menu bar). Run after every upstream merge.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
GENERATED=$(mktemp)
trap 'rm -f "$GENERATED"' EXIT
{
    echo "// GENERATED by scripts/gen-compositorapp-override.sh from Compositor/CompositorApp.swift — do not edit."
    echo "// Changes: #selector(T.m(_:)) -> Selector((\"m:\")); @main removed. See the script for why."
    sed -E -e 's/#selector\(([A-Za-z]+)\.([A-Za-z]+)\(_:\)\)/Selector(("\2:"))/g' -e '/^@main$/d' \
        "$ROOT/Compositor/CompositorApp.swift" | sed '/\.disabled(!session.canSelectSubject)/a\
                    Button("Color Range…") { session.beginColorRange() }\
                        .disabled(!session.canSelectColorRange)'
} > "$GENERATED"
if tail -n +3 "$GENERATED" | grep -q "#selector"; then
    echo "error: a #selector the script doesn't handle is left in CompositorApp.swift" >&2; exit 1
fi
if [ "${1:-}" = "--check" ]; then
    cmp -s "$GENERATED" "$ROOT/Sources/Overrides/CompositorApp.swift" || {
        echo "CompositorApp override is stale; run scripts/gen-compositorapp-override.sh" >&2; exit 1;
    }
elif ! cmp -s "$GENERATED" "$ROOT/Sources/Overrides/CompositorApp.swift"; then
    cp "$GENERATED" "$ROOT/Sources/Overrides/CompositorApp.swift"
fi
