#!/usr/bin/env python3
"""Expose the upstream compositor's adjustment scale without editing macOS source."""
import argparse
from pathlib import Path

root = Path(__file__).resolve().parents[1]
source = (root / "Compositor/IO/ImageExporter.swift").read_text()
start = source.index("    func render(_ snapshot: ProjectSnapshot)")
end = source.index("    func pngData(", start)
method = source[start:end]
signature = "func render(_ snapshot: ProjectSnapshot)"
anchor = "            live.adjustment = { records[$0]?.adjustment }"
assert method.count(signature) == 1 and method.count(anchor) == 1, "Upstream renderer changed"
method = method.replace(signature, "func renderPreview(_ snapshot: ProjectSnapshot, scale: CGFloat)")
method = method.replace(anchor, "            live.adjustmentScale = scale\n" + anchor)
output = (
    "// GENERATED by scripts/gen-preview-renderer.py from Compositor/IO/ImageExporter.swift.\n"
    "// Only the entry point and per-render adjustment scale differ from upstream.\n"
    "import Foundation\nimport CoreGraphics\n\nextension ImageExporter {\n" + method + "}\n"
)
target = root / "Sources/LinuxBridge/PreviewRenderer.swift"
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
if args.check:
    if not target.exists() or target.read_text() != output:
        raise SystemExit("Linux preview renderer is stale; run scripts/gen-preview-renderer.py")
else:
    target.write_text(output)
