#!/usr/bin/env python3
"""Cache the unchanged radial falloff on Linux; retain the upstream stroke algorithm.

Run after upstream merges. --check rejects stale generated sources. The unmodified
class also builds as a test oracle so complete strokes can be compared byte for byte.
"""
import argparse
from pathlib import Path

root = Path(__file__).resolve().parents[1]
source = (root / 'Compositor/Document/SmudgeLiquify.swift').read_text()
anchor = '    private var scratch: [Float] = []\n'
assert source.count(anchor) == 1, 'Upstream scratch declaration changed'
cache = '''
    /// A fixed tip revisits the same integer squared distances at every dab. Cache their
    /// exact upstream falloff; cap storage at 512 KiB for common tips and retain the
    /// scalar path for larger tips, including large brushes on tiny canvases.
    private lazy var radialWeights: [Float]? = {
        let r = radius
        guard r <= 256 else { return nil }
        let invR = 1 / Float(diameter / 2)
        return (0...(2 * r * r)).map { weight(Float($0).squareRoot() * invR) }
    }()
'''
optimized = source.replace(anchor, anchor + cache)
for signature in ['    private func smudge(at center: CGPoint) {\n',
                  '    private func push(from a: CGPoint, to b: CGPoint) {\n']:
    assert optimized.count(signature) == 1, 'Upstream stroke method changed'
    optimized = optimized.replace(signature, signature + '        let weights = radialWeights\n')
old = 'let w = weight(Float(dx * dx + dy * dy).squareRoot() * invR)'
assert optimized.count(old) == 2, 'Upstream falloff expression changed'
optimized = optimized.replace(old, 'let w = weights?[dx * dx + dy * dy] ?? weight(Float(dx * dx + dy * dy).squareRoot() * invR)')
header = '// GENERATED by scripts/gen-smudge-liquify-override.py; regenerate after upstream merges.\n'
outputs = {
    root / 'Sources/Overrides/SmudgeLiquify.swift': header + optimized,
    root / 'Tests/LinuxOverrideTests/ReferenceWarpStroke.swift': header + 'import AppKit\n@testable import Compositor\n\n@MainActor\n' +
        source[source.index('final class WarpStroke {'):source.index('\nextension EditorSession {')]
        .replace('final class WarpStroke {', 'final class ReferenceWarpStroke {', 1),
}
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
for path, content in outputs.items():
    if args.check:
        assert path.read_text() == content, f'Stale generated source: {path}'
    else:
        path.write_text(content)
