#!/usr/bin/env python3
"""Expose the upstream metadata rules to the Linux raw-manifest ABI without editing upstream."""
import argparse
from pathlib import Path

root = Path(__file__).resolve().parents[1]
# Prefer tip ProjectStore when Linux no longer overrides it (format 11 already upstream).
for candidate in [
    root / "Sources/Overrides/ProjectStore.swift",
    root / "Compositor/IO/ProjectStore.swift",
]:
    if candidate.exists():
        source_path = candidate
        break
else:
    raise SystemExit("ProjectStore.swift not found")
source = source_path.read_text()
start = source.index("    private func validate(_ manifest:")
end = source.index("    private func checkSize(", start)
methods = source[start:end].replace("private func validate(", "static func validate(").replace(
    "private func validateGuides(", "private static func validateGuides(")
output = (
    f"// GENERATED by scripts/gen-project-validation.py from {source_path.relative_to(root)}.\n"
    "// Run --check after upstream merges to detect changed validation rules.\n"
    "import Foundation\n\n"
    "enum LinuxProjectValidation {\n" + methods + "}\n"
)
target = root / "Sources/LinuxBridge/LinuxProjectValidation.swift"
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
if args.check:
    if not target.exists() or target.read_text() != output:
        raise SystemExit("Linux project validation is stale; run scripts/gen-project-validation.py")
else:
    target.write_text(output)
