#!/usr/bin/env bash
# Regenerates Sources/Overrides/CompositorApp.swift from upstream's Compositor/CompositorApp.swift. The only changes
# are mechanical: `#selector(Type.method(_:))` becomes `Selector(("method:"))` (Linux Swift has no Objective-C
# runtime, so `#selector` cannot compile), and `@main` goes (the Linux entry point is CompositorHostBootstrap; the
# shell reads the app's `.commands` to build its menu bar). Run after every upstream merge.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
{
    echo "// GENERATED by scripts/gen-compositorapp-override.sh from Compositor/CompositorApp.swift — do not edit."
    echo "// Changes: #selector(T.m(_:)) -> Selector((\"m:\")); @main removed. See the script for why."
    sed -E -e 's/#selector\(([A-Za-z]+)\.([A-Za-z]+)\(_:\)\)/Selector(("\2:"))/g' -e '/^@main$/d' \
        "$ROOT/Compositor/CompositorApp.swift"
} > "$ROOT/Sources/Overrides/CompositorApp.swift"
if tail -n +3 "$ROOT/Sources/Overrides/CompositorApp.swift" | grep -q "#selector"; then
    echo "error: a #selector the script doesn't handle is left in CompositorApp.swift" >&2; exit 1
fi
