#!/usr/bin/env python3
"""Apply pinned upstream mixed-font support to Linux-owned sources only.

The vendored patch is the exact TypeTool, ProjectStore and TypeToolTests diff
from 2309a85 to c28f827385303c4b90480b9e18d0b645c79acd5e (upstream 1.3.4).
No Git history or network is needed when regenerating from a source archive.
"""
import argparse
from pathlib import Path
import subprocess
import tempfile

root = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
mapping = {
    'Compositor/Document/TypeTool.swift': 'Sources/Overrides/TypeTool.swift',
    'Compositor/IO/ProjectStore.swift': 'Sources/Overrides/ProjectStore.swift',
    'CompositorTests/TypeToolTests.swift': 'Tests/LinuxOverrideTests/TypeToolTests.swift',
}
header = '// GENERATED by scripts/gen-text-format-11.py; see linux/patches/text-format-11.patch.\n'
outputs = {}
with tempfile.TemporaryDirectory() as directory:
    staging = Path(directory)
    for source in mapping:
        target = staging / source
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text((root / source).read_text())
    subprocess.run(['patch', '--batch', '--fuzz=0', '-p1', '-d', directory,
                    '-i', str(root / 'linux/patches/text-format-11.patch')], check=True,
                   stdout=subprocess.DEVNULL)
    for source, target in mapping.items():
        outputs[target] = header + (staging / source).read_text()
# Keep every existing assertion in these suites, updating only the writer version.
for name in ['GroupTests', 'LayerMaskTests', 'LayerAppearanceTests']:
    source = (root / f'CompositorTests/{name}.swift').read_text()
    assert 'manifest.version == 10' in source, f'{name}: version assertion changed'
    outputs[f'Tests/LinuxOverrideTests/{name}.swift'] = header + source.replace(
        'manifest.version == 10', 'manifest.version == 11')
# GroupTests uses the original test module's image factory. Copy only that helper,
# not its tests, into this module so its fixture and assertions stay identical.
fixture = (root / 'CompositorTests/ImageImportTests.swift').read_text()
outputs['Tests/LinuxOverrideTests/ImageImportFixture.swift'] = header + fixture[:fixture.index('    @Test')] + '}\n'
for target, content in outputs.items():
    path = root / target
    if args.check:
        assert path.read_text() == content, f'Stale generated source: {target}'
    else:
        path.write_text(content)
