#!/usr/bin/env python3
"""Keep Linux format-11 test mirrors in sync with the protected tip.

When tip is still pre-1.3.4, applies linux/patches/text-format-11.patch onto TypeTool /
ProjectStore / TypeToolTests into Sources/Overrides and Tests/LinuxOverrideTests.
When tip already includes format 11 (version assertions at 11, fontRuns present), tip
TypeTool and ProjectStore compile directly (not overridden); only the LinuxOverrideTests
mirrors are refreshed from tip.
"""
import argparse
from pathlib import Path
import subprocess
import tempfile

root = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--check', action='store_true')
args = parser.parse_args()

tip_type = (root / 'Compositor/Document/TypeTool.swift').read_text()
tip_already_11 = 'fontRuns' in tip_type and 'manifest.version == 11' in (
    root / 'CompositorTests/GroupTests.swift').read_text()

header = '// GENERATED by scripts/gen-text-format-11.py; see linux/patches/text-format-11.patch.\n'
outputs = {}

if tip_already_11:
    # Tip owns TypeTool / ProjectStore; keep LinuxOverrideTests mirrors byte-identical to tip suites.
    for name in ['TypeToolTests', 'GroupTests', 'LayerMaskTests', 'LayerAppearanceTests']:
        source = (root / f'CompositorTests/{name}.swift').read_text()
        outputs[f'Tests/LinuxOverrideTests/{name}.swift'] = header + source
    fixture = (root / 'CompositorTests/ImageImportTests.swift').read_text()
    outputs['Tests/LinuxOverrideTests/ImageImportFixture.swift'] = (
        header + fixture[:fixture.index('    @Test')] + '}\n')
    # Stale Overrides from older catch-ups must not linger (Package compiles tip files).
    for stale in ['Sources/Overrides/TypeTool.swift', 'Sources/Overrides/ProjectStore.swift']:
        path = root / stale
        if path.exists():
            if args.check:
                raise SystemExit(f'Stale override must be removed: {stale}')
            path.unlink()
else:
    mapping = {
        'Compositor/Document/TypeTool.swift': 'Sources/Overrides/TypeTool.swift',
        'Compositor/IO/ProjectStore.swift': 'Sources/Overrides/ProjectStore.swift',
        'CompositorTests/TypeToolTests.swift': 'Tests/LinuxOverrideTests/TypeToolTests.swift',
    }
    with tempfile.TemporaryDirectory() as directory:
        staging = Path(directory)
        for source in mapping:
            target = staging / source
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text((root / source).read_text())
        subprocess.run(['patch', '--batch', '--fuzz=0', '-p1', '-d', directory,
                        '-i', str(root / 'linux/patches/text-format-11.patch')], check=True,
                       stdout=subprocess.DEVNULL)
        for source, target in mapping.items():
            outputs[target] = header + (staging / source).read_text()
    for name in ['GroupTests', 'LayerMaskTests', 'LayerAppearanceTests']:
        source = (root / f'CompositorTests/{name}.swift').read_text()
        assert 'manifest.version == 10' in source, f'{name}: version assertion changed'
        outputs[f'Tests/LinuxOverrideTests/{name}.swift'] = header + source.replace(
            'manifest.version == 10', 'manifest.version == 11')
    fixture = (root / 'CompositorTests/ImageImportTests.swift').read_text()
    outputs['Tests/LinuxOverrideTests/ImageImportFixture.swift'] = (
        header + fixture[:fixture.index('    @Test')] + '}\n')

for target, content in outputs.items():
    path = root / target
    if args.check:
        assert path.read_text() == content, f'Stale generated source: {target}'
    elif not path.exists() or path.read_text() != content:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
