#!/usr/bin/env python3
"""Generates host/LucideIcons.h: the Lucide SVGs (third_party/lucide/icons) the UI uses, keyed by the SF Symbol names
upstream writes (third_party/lucide/icons.map). SwiftPM can't run Qt's rcc, so the icons are compiled in as strings."""
import pathlib, re
root = pathlib.Path(__file__).resolve().parent.parent
pairs = [l.split() for l in (root / "third_party/lucide/icons.map").read_text().splitlines() if l.strip() and not l.startswith("#")]
out = ["// GENERATED by scripts/gen-lucide-icons.py — do not edit. Lucide icons (ISC, third_party/lucide/LICENSE).",
       "#pragma once", "#include <QHash>", "#include <QByteArray>", "#include <QString>", "",
       "/// SVG source for an SF Symbol name upstream uses, drawn from Lucide (the stand-in for SF Symbols); empty if none.",
       "inline QByteArray lucideIconSVG(const QString &symbol) {", "    static const QHash<QString, QByteArray> icons{"]
for sf, name in pairs:
    svg = (root / "third_party/lucide" / (f"{name}.svg" if name.startswith("custom/") else f"icons/{name}.svg")).read_text()
    svg = re.sub(r"<!--.*?-->", "", svg, flags=re.S)
    svg = re.sub(r'\s*class="[^"]*"', "", svg)
    svg = " ".join(svg.split())
    out.append(f'        {{QStringLiteral("{sf}"), QByteArrayLiteral(R"svg({svg})svg")}},')
out += ["    };", "    return icons.value(symbol);", "}", ""]
(root / "host/LucideIcons.h").write_text("\n".join(out))
