#!/usr/bin/env bash
# Writes host/AppVersion.h from the Xcode project's MARKETING_VERSION / CURRENT_PROJECT_VERSION, so the Linux About
# panel shows the version the Mac app does. Run after every upstream merge.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PBX="$ROOT/Compositor.xcodeproj/project.pbxproj"
VERSION="$(sed -n 's/.*MARKETING_VERSION = \([^;]*\);/\1/p' "$PBX" | head -1)"
BUILD="$(sed -n 's/.*CURRENT_PROJECT_VERSION = \([^;]*\);/\1/p' "$PBX" | head -1)"
cat > "$ROOT/host/AppVersion.h" <<H
// GENERATED by scripts/sync-version.sh from Compositor.xcodeproj — do not edit.
#pragma once
#define COMPOSITOR_VERSION "$VERSION"
#define COMPOSITOR_BUILD "$BUILD"
H
