// GENERATED by scripts/gen-color-range.py; see linux/patches/color-range.patch.
// GENERATED by scripts/gen-color-range.py — color_range_mask is defined in
// Compositor/Rendering/WandPixels.c (CompositorKernels). Tip 1.3.4+ already ships it;
// this unit stays empty so CompositorSelectionBackend still has a compile unit and header.
#include "ColorRange.h"
