// GENERATED by scripts/gen-smudge-liquify-override.py; regenerate after upstream merges.
import AppKit

/// The Blur tool's modes. Smudge and Liquify push the active layer's pixels around under the brush.
/// The Brush tool's modes.
nonisolated enum BrushToolMode: String, CaseIterable, Sendable {
    case paint = "Paint"
    case erase = "Erase"
}

nonisolated enum BlurToolMode: String, CaseIterable, Sendable {
    case liquify = "Liquify"
    case blur = "Blur"
    case smudge = "Smudge"
}

/// A Smudge or Liquify stroke in progress. It works on the active layer as the canvas shows it, at document size,
/// changing it dab by dab; the canvas shows that working copy in place of the layer. When the stroke ends, the result
/// is painted into the layer's own pixels along the stroke's path (see `EditorSession.finishWarp`).
final class WarpStroke {
    let layer: ImageLayer
    let mode: BlurToolMode
    let diameter: CGFloat
    let hardness: CGFloat
    let strength: CGFloat
    let width: Int
    let height: Int
    let context: CGContext
    private let pixels: UnsafeMutablePointer<UInt8>
    /// Every dab's center, for painting the result into the layer.
    private(set) var points: [CGPoint] = []
    /// The working copy on the GPU, where the dabs run when there is one (see MetalWarp).
    let gpu: MetalWarp?
    private var cpuImage: CGImage?
    /// The working copy as an image, fetched from the GPU the first time it's asked for after a dab.
    var image: CGImage? {
        if let gpu {
            if cpuImage == nil {
                gpu.read(into: context)
                cpuImage = context.makeImage()
            }
            return cpuImage
        }
        // CPU smudge path: rebuild only on commit / full snapshot, not after every dab chunk.
        if cpuImage == nil { cpuImage = context.makeImage() }
        return cpuImage
    }
    private var last: CGPoint?
    /// Smudge: the color the brush carries, a (2r+1)² RGBA square.
    private var carried: [Float] = []
    private var scratch: [Float] = []

    /// A fixed tip revisits the same integer squared distances at every dab. Cache their
    /// exact upstream falloff; cap storage at 512 KiB for common tips and retain the
    /// scalar path for larger tips, including large brushes on tiny canvases.
    /// Built in `init` (not lazily) so the first measured dab does not pay the 32k-entry fill.
    private let radialWeights: [Float]?
    /// When a long jump needs more dabs than one turn's budget, the remaining target waits here
    /// so the shell can paint mid-stroke (see `continuePending` / `flushPending`).
    private var pendingTarget: CGPoint?

    init(layer: ImageLayer, image: CGImage, transform: LayerTransform, canvas: CGSize, mode: BlurToolMode, settings: BrushSettings,
         useGPU: Bool = true) throws {
        self.layer = layer
        self.mode = mode
        diameter = max(2, settings.diameter)
        hardness = min(0.98, max(0, settings.hardness))
        strength = min(1, max(0.01, settings.opacity))
        width = Int(canvas.width); height = Int(canvas.height)
        context = try BrushRaster.context(width: width, height: height, mask: false)
        LayerRenderer.draw(image, transform: transform, center: transform.center, in: context)
        guard let data = context.data else { throw ExportError.render }
        // Top-left rows: a document point's row is its y.
        pixels = data.bindMemory(to: UInt8.self, capacity: width * height * 4)
        // Smudge uses the CPU dab path below (cached radialWeights). MetalWarp is for Liquify's
        // sharp offset warp; its smudge body recomputed falloff every pixel and stalled live feedback.
        gpu = useGPU && mode != .smudge ? MetalWarp(pixels: context) : nil
        // Defer full-canvas makeImage: building it on press delayed Liquify first-feedback past 150 ms.
        // Live preview uses snapshot(in:); commit still goes through image when needed.
        cpuImage = nil
        let r = Int((diameter / 2).rounded(.up))
        if r <= 256 {
            let invR = 1 / Float(diameter / 2)
            let h = Float(hardness)
            radialWeights = (0...(2 * r * r)).map { i in
                let u = Float(i).squareRoot() * invR
                guard u < 1 else { return 0 }
                guard u > h else { return 1 }
                let t = (1 - u) / (1 - h)
                return t * t * (3 - 2 * t)
            }
        } else {
            radialWeights = nil
        }
    }

    private var radius: Int { Int((diameter / 2).rounded(.up)) }
    /// How much a dab moves pixels at a distance `u` (0 center, 1 rim) from its center.
    private func weight(_ u: Float) -> Float {
        guard u < 1 else { return 0 }
        let h = Float(hardness)
        guard u > h else { return 1 }
        let t = (1 - u) / (1 - h)
        return t * t * (3 - 2 * t)
    }

    /// Continues the stroke to `point`, dabbing along the way, then refreshes `image`.
    /// Long jumps are chunked (`dabBudget`) so the Qt shell can dirty-blit before the rest runs.
    var hasPendingDabs: Bool { pendingTarget != nil }

    func append(_ point: CGPoint) {
        appendToward(point, maxDabs: dabBudget)
    }

    /// Runs another budgeted slice toward `pendingTarget`. Returns whether more work remains.
    @discardableResult
    func continuePending() -> Bool {
        guard let target = pendingTarget else { return false }
        appendToward(target, maxDabs: dabBudget)
        return pendingTarget != nil
    }

    /// Drains every deferred dab before commit / cancel so the finished stroke matches a sync append.
    func flushPending() {
        while pendingTarget != nil { appendToward(pendingTarget!, maxDabs: 10_000) }
    }

    /// Smudge spacing is ~5× denser than Liquify; keep CPU time per turn inside the 150 ms feedback budget.
    /// Four dabs (~5 px at a 256 px tip) is enough for the live-feedback edge sample to change.
    private var dabBudget: Int { mode == .smudge ? 4 : 48 }

    private func appendToward(_ point: CGPoint, maxDabs: Int) {
        guard let from = last else {
            last = point
            pendingTarget = nil
            if mode == .smudge {
                if let gpu { gpu.pickUp(at: point, radius: radius); gpu.commit() } else { pickUp(at: point) }
            }
            return
        }
        let distance = hypot(point.x - from.x, point.y - from.y)
        // Smudge drags the pixels one dab's spacing at a time and mixes them with what's there: spaced widely, each step
        // left a faint copy of what it dragged, echoes along the stroke. A pixel apart (a little more for a huge brush)
        // the steps run together into one smear, as Photoshop's does.
        let spacing = max(1, diameter * (mode == .smudge ? 0.005 : 0.025))
        guard distance >= spacing else { pendingTarget = nil; return }
        let steps = Int((distance / spacing).rounded(.up))
        var previous = from
        var done = 0
        for step in 1...steps {
            let t = CGFloat(step) / CGFloat(steps)
            let next = CGPoint(x: from.x + (point.x - from.x) * t, y: from.y + (point.y - from.y) * t)
            if let gpu {
                if mode == .smudge { gpu.smudge(at: next, radius: radius, diameter: diameter, hardness: hardness, strength: strength) }
                else { gpu.push(from: previous, to: next, radius: radius, diameter: diameter, hardness: hardness, strength: strength) }
            } else if mode == .smudge { smudge(at: next) } else { push(from: previous, to: next) }
            points.append(next)
            previous = next
            done += 1
            if done >= maxDabs && step < steps {
                last = next
                pendingTarget = point
                if let gpu { gpu.commit() }
                cpuImage = nil
                return
            }
        }
        last = point
        pendingTarget = nil
        if let gpu { gpu.commit() }
        cpuImage = nil
    }

    /// Document-pixel crop of the working buffer without building a full-canvas CGImage.
    /// Linux live preview calls this every frame for the dirty tip; full `image` stays for commit.
    func snapshot(in region: CGRect) -> CGImage? {
        let bounds = CGRect(x: 0, y: 0, width: width, height: height)
        let crop = region.integral.intersection(bounds)
        guard !crop.isNull, crop.width >= 1, crop.height >= 1 else { return nil }
        if crop == bounds { return image }
        // MetalWarp mutates the same context buffer; commit is a no-op, then copy only the tip.
        if let gpu { gpu.commit() }
        let w = Int(crop.width), h = Int(crop.height)
        let srcX = Int(crop.minX), srcY = Int(crop.minY)
        guard let out = try? BrushRaster.context(width: w, height: h, mask: false),
              let dest = out.data else { return nil }
        let srcRow = context.bytesPerRow, dstRow = out.bytesPerRow
        for row in 0..<h {
            memcpy(dest + row * dstRow, pixels + (srcY + row) * srcRow + srcX * 4, w * 4)
        }
        return out.makeImage()
    }

    /// Same tip crop as `snapshot(in:)`, but raw premultiplied RGBA8 (no CGImage) for the shell's dirty blit.
    func copyPremultiplied(in region: CGRect) -> (bytes: [UInt8], rect: CGRect)? {
        let bounds = CGRect(x: 0, y: 0, width: width, height: height)
        let crop = region.integral.intersection(bounds)
        guard !crop.isNull, crop.width >= 1, crop.height >= 1 else { return nil }
        if let gpu { gpu.commit() }
        let w = Int(crop.width), h = Int(crop.height)
        let srcX = Int(crop.minX), srcY = Int(crop.minY)
        var bytes = [UInt8](repeating: 0, count: w * h * 4)
        let srcRow = context.bytesPerRow
        bytes.withUnsafeMutableBytes { raw in
            guard let dest = raw.bindMemory(to: UInt8.self).baseAddress else { return }
            for row in 0..<h {
                memcpy(dest + row * w * 4, pixels + (srcY + row) * srcRow + srcX * 4, w * 4)
            }
        }
        return (bytes, crop)
    }

    private func pickUp(at center: CGPoint) {
        let r = radius, side = 2 * r + 1
        carried = [Float](repeating: 0, count: side * side * 4)
        let cx = Int(center.x.rounded()), cy = Int(center.y.rounded())
        for dy in -r...r {
            let y = cy + dy
            guard y >= 0, y < height else { continue }
            for dx in -r...r {
                let x = cx + dx
                guard x >= 0, x < width else { continue }
                let p = (y * width + x) * 4, c = ((dy + r) * side + dx + r) * 4
                for k in 0..<4 { carried[c + k] = Float(pixels[p + k]) }
            }
        }
    }

    private func smudge(at center: CGPoint) {
        let weights = radialWeights
        let r = radius, side = 2 * r + 1
        let cx = Int(center.x.rounded()), cy = Int(center.y.rounded())
        let keep = Float(strength), invR = 1 / Float(diameter / 2)
        for dy in -r...r {
            let y = cy + dy
            guard y >= 0, y < height else { continue }
            for dx in -r...r {
                let x = cx + dx
                guard x >= 0, x < width else { continue }
                let w = weights?[dx * dx + dy * dy] ?? weight(Float(dx * dx + dy * dy).squareRoot() * invR)
                guard w > 0 else { continue }
                let p = (y * width + x) * 4, c = ((dy + r) * side + dx + r) * 4
                for k in 0..<4 {
                    let under = Float(pixels[p + k])
                    // What was under the brush at the last dab, laid down here at the smudge's strength, as Photoshop
                    // does: all of it drags the pixels along; less mixes them with what's here, softening the trail.
                    let painted = under + (carried[c + k] - under) * w * keep
                    pixels[p + k] = UInt8(max(0, min(255, painted.rounded())))
                    // The brush then carries what it just left, and nothing older: holding on to what it picked up
                    // at the start stamped it again at every dab, a trail of ghost copies.
                    carried[c + k] = painted
                }
            }
        }
    }

    /// Forward warp: pixels under the brush move with it, most at its center, fading to none at its rim.
    private func push(from a: CGPoint, to b: CGPoint) {
        let weights = radialWeights
        let r = radius
        let move = SIMD2<Float>(Float(b.x - a.x), Float(b.y - a.y)) * Float(strength)
        let margin = Int(ceil(max(abs(move.x), abs(move.y)))) + 2
        let cx = Int(b.x.rounded()), cy = Int(b.y.rounded())
        // A copy of the area as it was before this dab, which the dab samples from.
        let x0 = max(0, cx - r - margin), x1 = min(width - 1, cx + r + margin)
        let y0 = max(0, cy - r - margin), y1 = min(height - 1, cy + r + margin)
        guard x0 <= x1, y0 <= y1 else { return }
        let cw = x1 - x0 + 1, ch = y1 - y0 + 1
        if scratch.count < cw * ch * 4 { scratch = [Float](repeating: 0, count: cw * ch * 4) }
        for y in 0..<ch {
            for x in 0..<cw {
                let p = ((y + y0) * width + x + x0) * 4, s = (y * cw + x) * 4
                for k in 0..<4 { scratch[s + k] = Float(pixels[p + k]) }
            }
        }
        let invR = 1 / Float(diameter / 2)
        for dy in -r...r {
            let y = cy + dy
            guard y >= y0, y <= y1 else { continue }
            for dx in -r...r {
                let x = cx + dx
                guard x >= x0, x <= x1 else { continue }
                let w = weights?[dx * dx + dy * dy] ?? weight(Float(dx * dx + dy * dy).squareRoot() * invR)
                guard w > 0 else { continue }
                // Bilinear sample of the old pixels, from behind the brush's travel.
                let sx = min(Float(cw - 1), max(0, Float(x - x0) - move.x * w))
                let sy = min(Float(ch - 1), max(0, Float(y - y0) - move.y * w))
                let ix = min(cw - 2, Int(sx)), iy = min(ch - 2, Int(sy))
                guard ix >= 0, iy >= 0 else { continue }
                let fx = sx - Float(ix), fy = sy - Float(iy)
                let p = (y * width + x) * 4
                let s00 = (iy * cw + ix) * 4, s10 = s00 + 4, s01 = s00 + cw * 4, s11 = s01 + 4
                for k in 0..<4 {
                    let top = scratch[s00 + k] + (scratch[s10 + k] - scratch[s00 + k]) * fx
                    let bottom = scratch[s01 + k] + (scratch[s11 + k] - scratch[s01 + k]) * fx
                    pixels[p + k] = UInt8(max(0, min(255, (top + (bottom - top) * fy).rounded())))
                }
            }
        }
    }
}

extension EditorSession {
    func beginWarp(at point: CGPoint) {
        guard canPaint, !isMaskSelected, let layer = activeLayer, let image = layer.asset?.image, let document else {
            brushError = isMaskSelected ? "Smudge and Liquify work on a layer's pixels, not its mask." : paintRefusal
            return
        }
        finishOpacityEdit()
        do {
            let stroke = try WarpStroke(layer: layer, image: image, transform: displayedTransform(for: layer),
                                        canvas: document.size, mode: blurMode, settings: brushSettings)
            stroke.append(point)
            warpStroke = stroke
            lastBrushPoint = (point, layer.id, false)
            brushRevision += 1
        } catch { brushError = error.localizedDescription }
    }

    /// Paints the finished Smudge or Liquify result into the layer's pixels along the stroke, as one undo step.
    func finishWarp() {
        guard let warp = warpStroke else { return }
        // Drain chunked dabs so commit matches a fully synchronous stroke.
        warp.flushPending()
        warpStroke = nil
        brushRevision += 1
        guard !warp.points.isEmpty else { return }
        // Commit only the stroke's dirty tip union — full-canvas makeImage + dense tip replay
        // was the ~1s release hang after long Liquify/Smudge strokes on Full HD.
        let pad = ceil(warp.diameter / 2) + 2
        var dirty = CGRect.null
        for point in warp.points {
            dirty = dirty.union(CGRect(x: point.x - pad, y: point.y - pad,
                                       width: pad * 2, height: pad * 2))
        }
        let canvas = CGRect(x: 0, y: 0, width: warp.width, height: warp.height)
        dirty = dirty.integral.intersection(canvas)
        guard !dirty.isNull, !dirty.isEmpty, let result = warp.snapshot(in: dirty),
              let current = document?.layers.first(where: { $0.id == warp.layer.id }),
              current.asset?.image === warp.layer.asset?.image, current.transform == warp.layer.transform else { return }
        do {
            var settings = brushSettings
            // Hard tip a little wider than the brush; sparse stamps still cover a solid tip.
            let tip = warp.diameter + 4
            settings.diameter = tip
            settings.hardness = 1
            settings.opacity = 1
            let stroke = try makeRasterEdit(for: current, settings: settings)
            stroke.clone = (result, dirty, false)
            stroke.replacesWithClone = true
            stroke.editName = warp.mode.rawValue
            // Hard circular tip of diameter `tip` covers when centers are ≤ tip apart; 0.05 was 10× denser
            // than needed and dominated release after intensive strokes.
            let spacing = max(1, tip * 0.5)
            var kept: CGPoint?
            for (index, point) in warp.points.enumerated() {
                if let kept, index < warp.points.count - 1, hypot(point.x - kept.x, point.y - kept.y) < spacing { continue }
                try stroke.append(point)
                kept = point
            }
            try stroke.flush()
            if !stroke.patches.isEmpty { try commitPaintSnapshot(stroke) }
        } catch { brushError = error.localizedDescription }
    }
}

extension EditorSession {
    /// Advances deferred WarpStroke dabs after a dirty frame. Returns whether more remain.
    @discardableResult
    func continueWarpPending() -> Bool {
        guard let warp = warpStroke, warp.hasPendingDabs else { return false }
        let more = warp.continuePending()
        brushRevision += 1
        return more
    }
}
